### ISSUE TITLE
Bug: Permacrash

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#103]
Ran into a permacrash, no real idea what happened; last I saw I was approaching a giant.

Apparently there's a panic save, maybe someone can spectate and get an error message or something.

**Comment by ThatGitMITZE** [comment]
Managed to trigger this a second time, approaching a snow troll. You want the save? Not sure if it'd be useful for debugging.

**Comment by NickMcConnell** [comment]
Yes, that might be useful

**Comment by ThatGitMITZE** [comment]
Unsure whether you had access to the webserver for the convo, but I think you'd have to ask Gwarl for it (it's under the MITZE account); I think the download save button on the server downloads the proper save, not the panic save.

**Comment by ThatGitMITZE** [comment]
Managed to finangle myself into a position where I can consistently reproduce the crash; still no idea what's causing it though.

Posted the save in the thread on oook, hopefully there's something useful in that.

**Comment by NickMcConnell** [comment]
I need to load commit 3ddb8ecce some time to check this out, as savefiles broke after that.

**Comment by NickMcConnell** [comment]
All right, this looks like a bug in the queueing code in z-queue.c, possibly caused by the queue getting too big (taht's mostly a guess).

**Comment by NickMcConnell** [comment]
OK, having consulted with the author of the queueing code, it's definitely crashing because of a failsafe for if the queue gets too long, but I don't believe the queue *is* getting too long (doubling its length still gives the same crash).  Which makes it look like the error is in update_flow(), but I can't see it.  Yet.
