### ISSUE TITLE
Bug: Stat Calculations

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#114]
Stat calculations (or at least the display for thereof) seem to be bugged too; as per my character sheet right now, I have:

STR: 4 = 3 + 1 (correct, I started with 3 STR and have +1 from a pair of gauntlets)
DEX: 5 (incorrect, I started with 4 and have +1 from the Evasion tree, this isn't reflected)
CON: 4 = 0 + 1 (incorrect, I started with 3 and have +1 from an amulet, no idea where the 0 is coming from)
GRA: 4 (incorrect, I started with 3 and have +1 from the Perception tree, this isn't reflected)

**Comment by NickMcConnell** [comment]
This is due to a different way of adding up the stats, so it is a display issue only; still needs fixing.
