### ISSUE TITLE
Monster status

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/NarSil#117]
If I "look" at a monster it doesn't say whether it's asleep, unwary etc. Edit well it does in term-4 but not in Narsil window Edit: I notice that once you engage the monster it says e.g. fleeing under the line of health asterix so the difference is in Sil-Q 1.5 it shows sleeping or unwary in that spot on screen as you "look" before you engage.

**Comment by NickMcConnell** [comment]
I believe this only shows (both in Sil 1.3 and in Sil-Q 1.5) when the player is in wizard mode.

**Comment by davidk64fnq** [comment]
![Screenshot 2023-04-25 212536](https://user-images.githubusercontent.com/63939880/234262484-d5925565-5cad-496d-ba1a-5d71d45a98aa.png
I wouldn't know how to get into wizard mode :0

**Comment by NickMcConnell** [comment]
I get it now.
