### ISSUE TITLE
Main window display using bigger font

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/NarSil#118]
If I have the term-0 window font set to 16x24 and look at help the list of commands is cut off - can't scroll down to see bottom part of list Edit: this affects seeing status line at bottom of main window as well i.e. with larger font can't see light level, depth etc at bottom of screen. Also if message on top line is wider than the screen it doesn't wrap but I can read full message in term-1 okay. I think this happens in sil-Q 1.5 as well.

**Comment by NickMcConnell** [comment]
Haven't touched it.
