### ISSUE TITLE
Search?

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/NarSil#119]
In Sil-Q 1.5 shift S lets me search for secret doors - how do I do it in Narsil? Edit: or is it like Angband where you don't have to search anymore?

**Comment by NickMcConnell** [comment]
'S' toggles stealth mode in Sil-Q, I believe.  Standing still and resting both do a search every turn.

There is a do_cmd_search() function in both Sil and NarSil, both of which do nothing - I need to remove that from NarSil.

**Comment by davidk64fnq** [comment]
I came to a dead end against a right angles corridor and held the 5 key down for a few seconds but it didn't find a secret door. Wondering whether 5 is searching?

**Comment by NickMcConnell** [comment]
Yes, it's stand still which does a turn of searching.

**Comment by davidk64fnq** [comment]
[treeRoute.zip](https://github.com/NickMcConnell/NarSil/files/11357835/treeRoute.zip)
Here's an example where I think there would be a secret door but pressing 5 doesn't find it?

**Comment by NickMcConnell** [comment]
There is no secret door there - it's an instance of #68.

**Comment by davidk64fnq** [comment]
[treeRoute.zip](https://github.com/NickMcConnell/NarSil/files/11360700/treeRoute.zip)
What about here?

**Comment by NickMcConnell** [comment]
Yes, that's wall too.

**Comment by davidk64fnq** [comment]
Finally found a secret door with "5" - happy now!
