### ISSUE TITLE
Morale bonus for similar creature in line of sight

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/NarSil#122]
Sil-Q 1.5 says (page 19) monsters get +1 for similar creatures in line of sight that are not fleeing. I tried luring an attacking monster from one room where it had friends to another room where it was alone and its morale score didn't change - I thought it would decrease by 2 for the two now out of sight mates. Just wondering if this is intended to be in Narsil? Edit: it seems to be working most of the time. However I moved from one room to another with two in the room and one in the doorway. The doorway monster was getting +2 when all three were in the same room but not when he was in the doorway, once he moved into the room he got the +2 again. I guess it's all to do with the line of sight algorithm.

Edit: Noticing monsters labeled aggressive but their morale is not > 20? Sil-Q 1.5 manual page 20. Is it that once a monster turns aggressive it never goes back to confident even if morale drops below 20? Might be that the label is not getting refreshed.

Edit: I have a monster whose health dropped below 25% taking his morale to 0 so started fleeing but on subsequent turns he didn't keep fleeing instead stayed put and attacked me. His moral increasing by 1 each turn in line with the 10% decay of fleeing penalty. But on term-1 he continues to be labeled as fleeing. I'm not sure why he didn't keep fleeing as his morale should be below 0 for a number of turns while the penalty decays.

Edit: keep seeing monsters with negative morale in fleeing status change to confident with high morale that I can't explain by my understanding of how morale is calculated based on 1.5 manual description. I just had a case where turn a wolf was -6 fleeing, I moved adjacent to him and he became 14 aggressive, nothing else in the room. My health < 75% so it's as if the -6 fleeing penalty was cancelled, a +6 bonus for stop fleeing was applied to base 6 then +4 for my health status then maybe a -2 for his health? The odd part is how the morale goes from -6 to positive to then trigger the +6 not fleeing bonus in one turn if the fleeing penalty is supposed to decay 10% per turn.

**Comment by NickMcConnell** [comment]
Will check.

**Comment by davidk64fnq** [comment]
Another example to maybe help work out what's happening. I was in a corridor with orc at -9 morale and one space between us after hitting him to trigger fleeing. On next turn I moved adjacent in corridor and messages were orc panics, orc shouts a warning, orc turns to fight and now morale is 7 confident with two red asterix. When I hit him last turn a -6 penalty starts decaying 10% per turn. How can suddenly be morale +7, (my health 100%)

**Comment by davidk64fnq** [comment]
Another one a -5 fleeing went to 13 confident in one turn while I pressed 5 with nothing else in the room. I think the messages X panics followed by X turns to fight is a common indicator of this happening.

**Comment by NickMcConnell** [comment]
I'm going to close this because it looks likely to have been fixed in a similar way to #177.
