### ISSUE TITLE
Character creation

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/NarSil#124]
Not sure how closely Narsil is intended to follow Sil-Q 1.5 but I rolled up the build I've been playing in Sil-Q to compare and noticed the following"

- Narsil has my age as 3305
- the starting racial stats don't seem to be applied e.g. Fingolfin start with +1 dexterity but their first four skills (melee through stealth) are shown as 0 when they should be 1?
- Fingolfin get song affinity in Sil but not in Narsil
- the starting amounts of health and voice are different

**Comment by NickMcConnell** [comment]
Age looks fine, and Fingolfin get will affinity, not song.  The other things turn out OK in the end, but the display is incorrect during the birth process.

**Comment by davidk64fnq** [comment]
Agree - happy to close

**Comment by NickMcConnell** [comment]
I'll leave it open for now, and close it when I've sorted the display issues.

**Comment by NickMcConnell** [comment]
Closing this in favour of #181.
