### ISSUE TITLE
Setting options?

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/NarSil#125]
= doesn't work for me, it says type ? for help

**Comment by NickMcConnell** [comment]
Options are 'O' in the standard keyset, '=' in the angband-like.

**Comment by davidk64fnq** [comment]
The ? available commands doesn't have an entry for O

**Comment by NickMcConnell** [comment]
OK, the help is rubbish 😄 .  I'll file a separate bug for that.
