### ISSUE TITLE
SlowSlow

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/NarSil#128]
I stepped on a caltrop trap and was slowed, status line at bottom of term-0 shows "SlowSlow" is that intentional?

**Comment by ThatGitMITZE** [comment]
Not quite fixed? I step on a caltrop trap, the status line still displays, "Slow Slowed".

**Comment by NickMcConnell** [comment]
Yes, this is working as intended.  "Slow" means moving at 1 speed instead of the normal 2, and "Slowed" means the player has the temporary slow status.
