### ISSUE TITLE
Bug: Charge and Flanking

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#134]
Charge seems to be able to proc off of a Flanking attack; I don't think it's supposed to work that way, only if you move directly into an enemy after having moved towards it the previous turn.

**Comment by NickMcConnell** [comment]
In fact, Charge is explicitly allowed to work from a Flanking attack.

**Comment by ThatGitMITZE** [comment]
...it is? Huh. News to me, seems counterintuitive, but all right?

(I'm learning how little I actually know about Sil, doing all this bugtesting...)

**Comment by NickMcConnell** [comment]
You still know more than me 😄
