### ISSUE TITLE
Bug: Overquivering Arrows

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#135]
Adding enough arrows to a quiver stack so that there's more than the 99 maximum allowed, results in a weird message:

"You have 110 Arrows (1st l)."

As far as I can tell, everything worked fine otherwise; the excess arrows were deposited in the inventory, the quiver had 99.

**Comment by NickMcConnell** [comment]
It's telling you which clot the first pile of arrows is.

**Comment by NickMcConnell** [comment]
So I think this is actually done.
