### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by NickMcConnell** [NickMcConnell/NarSil#138]
The online manual now "[exists](https://narsil.readthedocs.io/en/latest/)", but is just the old Angband manual from when NarSil forked.

**Comment by bridgesense** [comment]
I would blank out the current manual completely. It could be clearer the way it is.  Most of those options don't pertain to Sil anyway.

**Comment by NickMcConnell** [comment]
I don't want to wipe it out completely, as there will be bits I do want to use.

Options are '=' in the Sil keyset and 'O' in the Angband keyset.

**Comment by NickMcConnell** [comment]
Actually, want this done pre-release.

**Comment by NickMcConnell** [comment]
I'm calling this done now.
