### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/NarSil#139]
[save.zip](https://github.com/NickMcConnell/NarSil/files/11321838/save.zip)
It happened after accessing abilities menu via tab key then escaping back to the game.

**Comment by NickMcConnell** [comment]
Interesting, looks like it could only arise because you had cleared all the objects from the level.

**Comment by NickMcConnell** [comment]
No, actually it was because you were the first to test Lore-Keeper.
