### ISSUE TITLE
Bug: Smithing/Requirements, Aren't

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#141]
Whatever you theoretically need, in terms of difficulty and abilities, doesn't actually stop you from making anything currently; with 5 total smithing and no abilities, I can still make, say, gloves of forging +2.

**Comment by ThatGitMITZE** [comment]
Actually not entirely accurate; looks like the uses are displayed in the menu, but not until you're at the deepest level of choosing a base object.

**Comment by ThatGitMITZE** [comment]
You can also forge mithril objects with no mithril on hand.

**Comment by NickMcConnell** [comment]
Should be all fixed by 32fa6bcae
