### ISSUE TITLE
Bug: Forging/Skill-Increasing Forgings

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#145]
...currently seem to have no experience cost; in Sil forging anything that increased a skill directly had a experience cost for doing so (at a rate of 100 exp per +1, so 100 for +1, 200 for +2, etc).

**Comment by NickMcConnell** [comment]
I believe they do, but it wasn't displayed.

**Comment by NickMcConnell** [comment]
Should be fixed by 32fa6bcae
