### ISSUE TITLE
Bug: Archery vs EV

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#147]
Archery doesn't appear to be rolling against half target native EV like it's supposed to. Note that this is specific to archery; throwing, as I understand it, is essentially melee at range (with adjustments to either target EV or actor ACC, unsure which, depending on range).

**Comment by NickMcConnell** [comment]
Any sense of what it *is* doing?

**Comment by ThatGitMITZE** [comment]
As far as I could tell, just using normal target EV.

I should note that I'm stating this after looking at the rolls subwindow, so it's possible that either there's a display issue there, or that I'm parsing it incorrectly.

**Comment by NickMcConnell** [comment]
Yes, the function that calculates monster evasion has an argument literally called "archery", and I was calling it with that set to false 🙄
