### ISSUE TITLE
Coding nit: function takes struct player* arg but uses player global

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#148]
These are the functions that I found that do that:

- combat.c's protection_roll()
- generate.c's cave_clear()
- gen-cave.c's cave_gen()
- mon-make.c's pick_and_place_monster_on_stairs()
- player-attack.c's whirlwind()
- player-birth.c's wield_all()
- player-path.c's run_test()
- player-util.c's player_radiates(), player_falling_damage(), player_can_leap(), player_break_web(), player_escape_pit(), player_blast_floor(), and search_square()
- ui-target.c's target_recall_loop_object(),

**Comment by NickMcConnell** [comment]
Thanks 😃
