### ISSUE TITLE
Bug: Smithing/Time Passage

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#150]
Smithing currently requires you to wait in place for however many turns; in Sil the time is automatically passed after you choose to start working, and you only get interrupted if you're otherwise disturbed e.g. by an enemy coming in.

**Comment by NickMcConnell** [comment]
I have seen it working properly; I will go back and check.

**Comment by NickMcConnell** [comment]
Yes, definitely working fine for me - was there anything else going on that might have affected it?

**Comment by ThatGitMITZE** [comment]
Nothing out of the ordinary for smithing; I just tested again and yep, I still have to wait in place.

(For posterity, this *is* on the webserver).

**Comment by NickMcConnell** [comment]
Looks like we're good.

**Comment by ThatGitMITZE** [comment]
Commenting for posterity that, I, at least, can't get this to cooperate with me. I'll leave you to decide whether to reopen.

**Comment by NickMcConnell** [comment]
Yes, it should be left open for now I think

**Comment by ThatGitMITZE** [comment]
Just as an FYI (and this isn't a complaint, just an observation), after giving some weeks for updates to happen and deleting all related webserver files under the profile before starting a new game, Smithing still doesn't want to work for me right as far as time passage goes. So, IDFK.

I'll probably see if I can get someone else to test on the webserver; if it works for you, and I've seen it work as it should exactly once and then never again, I have no idea where the problem could be is, I feel we might need new perspective on it.

**Comment by NickMcConnell** [comment]
Yeah, that's really odd.

**Comment by ThatGitMITZE** [comment]
Got wobbly to test on the webserver, it works fine for him, still doesn't for me. Tried flicking a bunch of options (like subwindows) on the off chance they're affecting it, no dice. I really don't have any idea.

**Comment by NickMcConnell** [comment]
So can you describe exactly what happens - messages, etc?

**Comment by ThatGitMITZE** [comment]
Not really much to say: wobbly confirms a smithing choice, game autoprogresses with the actual forging (presumably until/unless something like an enemy interrupts); I confirm a smithing choice, it just shunts me into the directional prompt, whereupon I have to hold down wait to progress the forging. If I exit out, and then go to forge again, it just shunts me into the direction prompt once more. @ me on the webserver if you want to see an example again personally.

**Comment by ThatGitMITZE** [comment]
Confirmed fixed, or at least it isn't acting up for me.
