### ISSUE TITLE
Out of bounds element index in display_combat_rolls()

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#152]
While testing out an implementation of the tutorial (compiled from source with the base of the changes for the tutorial as 8ffb9901e8015d741a697b75bb9407656b74515c ; compilation was done on macOS 12.6.5 with Apple's version of clang 14.0.0; OPT was set to "-g -O0 -fsanitize=address -fsanitize=undefined" when using Makefile.osx), the game crashed on an out-of-bounds access at ui-combat.c:301, "res = player->state.el_info[dam_type].res_level;".  dam_type was 6 (so out-of-bounds for el_info).  round and i were zero.  In case it matters, the attacker(s) were wolves.  Other combat (against a tanglethorn and orc soldiers) had occurred earlier with the player's character being hit and no crash happened for those combats.

The top of the call stack (omitting the address sanitizer routines) at the point of the crash was:
display_combat_rolls(type=EVENT_COMBAT_DISPLAY, data=0x0000000000000000, user=0x0000611000058c48) at ui-combat.c:301
update_combat_rolls_subwindow(type=EVENT_COMBAT_DISPLAY, data=0x0000000000000000, user=0x0000611000058c48
game_event_dispatch(type=EVENT_COMBAT_DISPLAY, data=0x0000000000000000) at game-event.c:43
event_signal(type=EVENT_COMBAT_DISPLAY) at game-event.c:142
redraw_stuff(p=0x000061a000024688) at player-calcs.c:1401
handle_stuff(p=0x000061a000024688) at player-calcs.c:1429
run_game_loop at game-world.c:1007
play_game(mode=GAME_TUTORIAL) at ui-game.c:932

I didn't have the combat rolls window open; only the main window was open.

**Comment by backwardsEric** [comment]
In the same environment as the original post, one way that combat_rolls[0][0].dam_type can be set to 6 is by the call to event_signal_combat_damage() at player-attack.c:513.  Since PROJ_HURT is 6, that ends up setting dam_type in the combat roll to 6.

**Comment by NickMcConnell** [comment]
I've only just taken in that you're implementing the tutorial.  How's it going?

**Comment by backwardsEric** [comment]
I'll likely put a pull request with the changes for the tutorial sometime this week.  The contents of the tutorial try to be faithful to Sil 1.3's tutorial.  As you noted in one of the outstanding issues, the monsters appear to be slower to wake.  For the tutorial, though, that could be caused by the initial values for the wakefulness or monster grouping not matching the values in Sil 1.3's tutorial savefile.

**Comment by NickMcConnell** [comment]
Amazing, thank you
