### ISSUE TITLE
Light query

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/NarSil#159]
Wielding a wooden torch which description says is radius 1 and intensity 1. The light number at bottom of term-0 window says 3 in lit rooms and 2 in corridors. Is that referring to the radius and do corridors have natural radius light of 2 then?

When I stop wielding torch figures change to 0 and -1 which implies wielding wooden torch is +3 to radius?

**Comment by NickMcConnell** [comment]
There is at least a display bug here which I have to track down - it's covered in #35.
