### ISSUE TITLE
Instability with level creation

### ISSUE THREAD

**Issue by wfpeterson79** [NickMcConnell/NarSil#16]
Attempting to change levels, either with stairs or the debug "j" command, will frequently cause a crash.
Occasionally, a dumpedlevel.html file is created. The one example I have has a label "Disconnected Level"
By using up and down stairs, and the debug command, I can get a character into the 3-400' range. Can't get any deeper.

**Comment by NickMcConnell** [comment]
Hangs sometimes on generation, too.

**Comment by NickMcConnell** [comment]
I'm hoping we're just about done here.  What I *really* should do is get stats working and run a large number of levels.

**Comment by NickMcConnell** [comment]
Haven't seen any problems here for a while.

**Comment by NickMcConnell** [comment]
Mostly seems fine, except for generating the throne room (and probably the gates).  Will leave open until those both work smoothly.

**Comment by backwardsEric** [comment]
Trying to jump to 1000 feet (and, if I got there, run the disconnection statistics to identify any problems) generates an assertion failure in my environment (macOS 12.6.5; compiled from source).  The backtrace at the point of the assertion is:

1. 0x0000000100034a6c narsil`square_in_bounds(c=0x0000000000000000, grid=(x = 52, y = 19)) at cave-square.c:822:2
2. 0x000000010064132d narsil`prt_map_aux at ui-map.c:633:10
3. 0x000000010063d7fc narsil`prt_map at ui-map.c:691:2
4. 0x00000001005aa69d narsil`update_maps(type=EVENT_MAP, data=0x00007ff7bfefbf40, user=0x00006110000606c8) at ui-display.c:1079:3
5. 0x000000010012885a narsil`game_event_dispatch(type=EVENT_MAP, data=0x00007ff7bfefbf40) at game-event.c:43:3
6. 0x0000000100128cc3 narsil`event_signal_point(type=EVENT_MAP, x=-1, y=-1) at game-event.c:160:2
7. 0x0000000100433276 narsil`redraw_stuff(p=0x000061a000015088) at player-calcs.c:1407:3
8. 0x00000001006a74c5 narsil`screen_save at ui-output.c:424:2
9. 0x00000001005bd1ec narsil`pause_with_text(type=EVENT_POEM, data=0x00007ff7bfefca00, user=0x0000000000000000) at ui-display.c:1560:2
10. 0x000000010012885a narsil`game_event_dispatch(type=EVENT_POEM, data=0x00007ff7bfefca00) at game-event.c:43:3
11. 0x000000010012c5d6 narsil`event_signal_poem(type=EVENT_POEM, name="throne_poetry", row=5, col=15) at game-event.c:363:2
12. 0x000000010015c788 narsil`throne_gen(p=0x000061a000015088) at gen-cave.c:1156:2
13. 0x00000001001497de narsil`cave_generate(p=0x000061a000015088) at generate.c:616:11
14. 0x0000000100146d77 narsil`prepare_next_level(p=0x000061a000015088) at generate.c:709:9
15. 0x0000000100141f0b narsil`run_game_loop at game-world.c:1037:5
16. 0x00000001005d9b2a narsil`play_game(mode=GAME_LOAD) at ui-game.c:932:4

It looks like redraw_stuff() or the downstream update_maps() will have to guard against cave being NULL or check character_dungeon.

**Comment by NickMcConnell** [comment]
Perhaps the right place is in textui_map_is_visible(), which should fix the problem in redraw_stuff().

**Comment by NickMcConnell** [comment]
I'm closing this now, as I think it's mostly sorted, and any problems on level creation would be better served y having a specific issue opened for them.
