### ISSUE TITLE
Names of the fallen options

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/NarSil#160]
When I died and was at the names of fallen screen it says any other key to continue but nothing happens when any other key pressed, esc goes to list of options

**Comment by NickMcConnell** [comment]
Yes, hitting a key just scrolls through the scores, you need to escape to get out.

**Comment by davidk64fnq** [comment]
I think there were instructions for scrolling the list in addition to the any other key directive - maybe delete the any other key message?

**Comment by NickMcConnell** [comment]
I think I want to make that option work sensibly.
