### ISSUE TITLE
Staff of warding

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/NarSil#169]
[treeRoute.zip](https://github.com/NickMcConnell/NarSil/files/11360794/treeRoute.zip)
When I use it with "u" i get "you failed to use the staff properly". with "A" I get type "?" for help

**Comment by NickMcConnell** [comment]
For the standard keyset, 'a' will use a staff, and 'u' will use any item.  For the angband-like, 'u' is for a staff and 'U' is for any item.  Unless you're using hjkl movement, in which case you need Ctrl-u for using any item.

The "you failed to use the staff properly" message means correct command, but your character's use of the staff failed.

**Comment by davidk64fnq** [comment]
Just noting the in game ? help has 'a' as aim a wand and 'A' as activate an object. Checking the 1.5 manual I see that use of staves is aided by will - I think I've been expecting staves to work automatically. Learnt something new!

**Comment by NickMcConnell** [comment]
Yes, the in-game help is completely wrong, I refer you to #137 😄
