### ISSUE TITLE
Staves, some work, some don't

### ISSUE THREAD

**Issue by wfpeterson79** [NickMcConnell/NarSil#17]
Here's what I've found
Staff of Understanding works
Entrapment doesn't work
Summoning doesn't work (not sure)
Recharging doesn't work
Earthquakes doesn't work (not sure)
Warding works, don't know whether the glyph works
Majesty works
Slumber might work, needs more testing
Foes works
Treasures works
Revelations works
Sanctity - can't test until a cursed object is available, maybe after smithing works
Light says it works, but need a dark room to be sure
Freedom doesn't completely work, even when message shows
Imprisonment only closes one door per activation, need to find a trap to test
Self Knowledge doesn't exist

**Comment by NickMcConnell** [comment]
This is really useful, thanks.

**Comment by NickMcConnell** [comment]
I've checked the Imprisonment code, and am happy it's OK - there's a separate skill check for each door.

**Comment by NickMcConnell** [comment]
Ditto with Freedom, there are skill checks for opening doors, removing traps and closing chasms, so variable results are expected.

**Comment by NickMcConnell** [comment]
Confirm Light works.

**Comment by NickMcConnell** [comment]
Slumber seems fine.

**Comment by NickMcConnell** [comment]
Glyphs of warding look like they work.

**Comment by NickMcConnell** [comment]
Earthquakes appears to work, but is kind of underwhelming; maybe the effect doesn't fully work.
Recharging looks like it's working fine.
Summoning is definitely working.
Entrapment is definitely working.

So summary, I'll leave this open until I check the earthquake effect, but then it can be closed I think.

**Comment by ThatGitMITZE** [comment]
I feel that I tried _Sanctity within the past week while wielding a cursed object and it didn't work.

**Comment by NickMcConnell** [comment]
Closing this any staff issues can be added to #90.
