### ISSUE TITLE
RFE: ability to avoid id game

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/NarSil#171]
In Sil 1.5 you can forge a ring of secrets requiring 1000 exp to get Jeweller ability, plus 1000 exp to get smithing up to 7 assuming 3 grace assigned when creating character. This also sets up for creating a Fenorian lamp if mithril is found, at no additional cost. In Narsil at present you need to invest 2800 exp in perception (regardless of character creation grace value) to get Lore-Master and that does nothing to prepare for creating the lamp. You would need an additional 1000 exp in smithing to get Jeweller. Admittedly Lore-Master gives all monster knowledge but you can get that as a game option in 1.5 for free anyways. As it stands in Narsil I feel you have to invest a disproportionate amount of starting exp in perception to avoid the id game at the cost of being underdone for melee and evasion in the early levels.

My request is either to make Lore-Master much cheaper, say 1000 exp, or make id staves and potions etc a game option.

**Comment by NickMcConnell** [comment]
The plan is for NarSil to have a first release of 1.3.0 which is gameplay identical (or close to it) to Sil 1.3.0.  Once that's done, I'll start thinking about what comes next.

Note that the main reason I started on Narsil was as a new game core for [Beleriand](https://github.com/NickMcConnell/Beleriand).

**Comment by ThatGitMITZE** [comment]
Also note David that Sil v1.5 doesn't exist, you're probably thinking of Sil-Q which is its own variant of Sil, by a different maintainer (Quirk) than those of the original Sil (Scatha and half).

Sil-Q's latest version, as far as I see, is v1.5, whereas Sil's last version was v1.3 and released years ago. Honestly, maybe someone should RFE Quirk that he makes it clear his thing is distinct from the original Sil in e.g. the startup screen (even though the window title bar offline blantantly states "Sil-Q").

**Comment by davidk64fnq** [comment]
Yes you're right! I am thinking of Sil-Q 1.5 and while I did know it was a variant, in practice I'd started thinking of it as a later version of Sil 1.3 - which as you say it's not. I've never played Sil 1.3 and only played a small amount of Sil-Q 1.5 but I really like it. That's probably why I've kept referring to it in new issues for Narsil. This reset in my thinking will help in any future testing of Narsil :)

**Comment by NickMcConnell** [comment]
Note that ID is completely revamped in the current main branch (which will be released fairly soon as 1.4.0), so this may no longer be relevant.

**Comment by davidk64fnq** [comment]
Yes, I've been following developments with interest! I'm happy for this to be closed if you are.

**Comment by NickMcConnell** [comment]
OK, done 😄
