### ISSUE TITLE
Out-of-bounds access: get_move()->projectable()

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#184]
On macOS 12.6.5 with e8cfd5df9518ad4ae7f5561c67cfb7eed80f598f compiled from source using "-g -O0 -DUSE_STATS -fsanitize=address -fsanitize=undefined" for OPT, there was a crash due to an out-of-bounds access in an encounter with some wolves.  The call stack at the point of the crash was:

1. 0x000000010048901d narsil`projectable(c=0x000060e000493508, grid1=(x = 65, y = 18), grid2=(x = 65, y = 20), flg=32768) at project.c:390:14
2. 0x00000001002838b3 narsil`get_move(mon=0x000000010df49978, tgrid=0x00007ff7bfefc5a0, fear=0x00007ff7bfefc5e0, must_use_target=false) at mon-move.c:1755:7
3. 0x0000000100270461 narsil`monster_turn(mon=0x000000010df49978) at mon-move.c:3457:8
4. 0x00000001002662fd narsil`process_monsters(minimum_energy=0) at mon-move.c:3719:3
5. 0x0000000100144e07 narsil`run_game_loop at game-world.c:1002:4
6. 0x00000001005ddaea narsil`play_game(mode=GAME_LOAD) at ui-game.c:9

According to the debugger, grid_n at the point of the crash was -2 and final and old_final were (65, 20).  Does project.c:390 need to use ABS(grid_n) like project.c:381?

**Comment by NickMcConnell** [comment]
I'm pretty sure that will be it - nice catch.
