### ISSUE TITLE
Out-of-bounds access: knock_back() calling dir_from_delta()

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#187]
With 6aa8ea936dd093bb8d3ad6d32942a3e22b4cd412 compiled from source on macOS (OPT was set to "-O0 -g -DUSE_STATS -fsanitize=address -fsanitize=undefined), the game crashed on an out-of-bounds access in an encounter with a mountain troll.  My character was at the end of dead end corridor; the troll was immediately next to my character (to the left if it matters).  The call stack at the point of the crash was:

1. 0x0000000100005cab narsil`dir_from_delta(delta_y=30, delta_x=72) at cave.c:327:10
2. 0x00000001000dc1a1 narsil`knock_back(grid1=(x = 70, y = 30), grid2=(x = 71, y = 30)) at combat.c:69:29
3. 0x00000001001f0a5d narsil`make_attack_normal(mon=0x000000010dd98f48, p=0x000061a000015088) at mon-attack.c:542:6
4. 0x000000010028c195 narsil`process_move(mon=0x000000010dd98f48, tgrid=(x = 71, y = 30), bash=false) at mon-move.c:2637:23
5. 0x00000001002719dd narsil`monster_turn(mon=0x000000010dd98f48) at mon-move.c:3512:2
6. 0x0000000100265d0d narsil`process_monsters(minimum_energy=101) at mon-move.c:3719:3
7. 0x0000000100145d61 narsil`run_game_loop at game-world.c:1054:4
8. 0x00000001005dd83a narsil`play_game(mode=GAME_LOAD) at ui-game.c:932:4

In knock_back(), dir was 6, i was 0, and mod was -1 at the point of the crash.

**Comment by NickMcConnell** [comment]
Nice report.
