### ISSUE TITLE
Stack buffer underflow in project_path()

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#195]
With 73161a845fa6d4106df298b9f595ccb979dff129 + https://github.com/NickMcConnell/NarSil/pull/193 compiled from source on macOS 12.6.5 (OPT was set to "-g -O0 -DUSE_STATS -fsanitize=address -fsanitize=undefined"), there was a crash because the address sanitizer detected a stack buffer underflow in project_path().  The character had backed down a corridor away from a room with some orc soldiers and orc archers in it.  The call stack at the point of the crash was:

1. 0x0000000100024460 narsil`project_path(c=0x000060e0005b3228, gp=0x00007ff7bfefa980, range=20, grid1=(x = 37, y = 8), grid2=0x00007ff7bfefa960, flg=8) at cave-fire.c:1351:12
2. 0x0000000100488409 narsil`projectable(c=0x000060e0005b3228, grid1=(x = 37, y = 8), grid2=(x = 30, y = 10), flg=8) at project.c:375:11
3. 0x00000001002c6282 narsil`remove_bad_spells(mon=0x000000010de94e48, f="\U00000001") at mon-spell.c:390:9
4. 0x00000001001eb673 narsil`choose_ranged_attack(mon=0x000000010de94e48) at mon-attack.c:113:2
5. 0x00000001001eaca6 narsil`make_ranged_attack(mon=0x000000010de94e48) at mon-attack.c:190:15
6. 0x000000010026d350 narsil`monster_turn(mon=0x000000010de94e48) at mon-move.c:3374:52
7. 0x0000000100265a2d narsil`process_monsters(minimum_energy=101) at mon-move.c:3719:3
8. 0x0000000100145a51 narsil`run_game_loop at game-world.c:1054:4
9. 0x00000001005dd69a narsil`play_game(mode=GAME_LOAD) at ui-game.c:932:4

At the point of the crash, step was 0, flg was 8, monster_in_way was false, require_strict_lof was true, dy was 2, dx was -7, dist was 8, vertical was false, octant was 3, slope_fire1 was 47, slope_fire2 was 48, bits0 through bits3 were 0, n_grids was 0, full_stop was false, grid was (x = 33, y = 11), old_grid was (x = 34, y = 9), and *grid2 was (x = 35, y = 11).

**Comment by backwardsEric** [comment]
The attached screen shot is the player's view of the dungeon at the point of the crash.
<img width="916" alt="Narsil-project_path_underflow" src="https://github.com/NickMcConnell/NarSil/assets/55062581/5011f9a6-5a70-4321-af16-038f7ed15a40">

**Comment by NickMcConnell** [comment]
I hate this algorithm so much

**Comment by NickMcConnell** [comment]
It seems to me that this error can only occur if the character's grid was not put into the projection path, and that should happen *every time*.  I'm concerned that something like the vinfo array might be getting its memory overwritten from elsewhere, because I can't see a logical way of n_grids still being 0 by the end of the function.

**Comment by NickMcConnell** [comment]
OK, I think [this line](https://github.com/NickMcConnell/NarSil/blob/4f8acf9fea8a7fbd5f1d63770e15b96689e9197b/src/cave-fire.c#L1215) is wrong.  square_isfire() is telling us whether the grid is projectable from the *player*, and in this case is failing for every grid on the path from monster to player as that path hits the wall of the room.

As far as I can see, this is also a bug in SIl and Sil-Q.  but I haven't checked that very thoroughly.  A possible solution here is to use the fact that projection paths are symmetric, and reverse the order of the grid arguments to projectable() in remove_bad_spells().

**Comment by backwardsEric** [comment]
I haven't seen any underflows since https://github.com/NickMcConnell/NarSil/commit/4f3ab902629991e7db58ec97fe1fcd112897a56a .  With regards to that change:

1. There are two places (player-attack.c and ui-target.c) where project_path() is called without going through projectable() so its conditions wouldn't have been enforced.  Both of those have the player in grid1 so project_path() could restore the logic associated with require_strict_lof but only set require_strict_lof to true if grid1 is the player.
2. For the checks associated with require_strict_lof in project_path() to be equivalent to those in projectable(), grid1 and grid2 having SQUARE_FIRE would have to imply that all the grids along the path from grid1 to grid2 have SQUARE_FIRE as well.  I haven't checked the logic of update_fire() against project_path() to know if that's true.

**Comment by backwardsEric** [comment]
With 8384c5ffb49109ce3782030dfdc7deea45f83dc9 + https://github.com/NickMcConnell/NarSil/pull/230 (compiled from source on macOS; OPT was "-g -O0 -DUSE_STATS -fsanitize=address -fsanitize=undefined"), there was a crash in ranged_helper() downstream from project_path() which may be related to this.  The cause of the crash was undefined behavior sanitizer complaining about an out of bounds index.  The call stack at the point of the crash was:

1. ranged_helper(p=0x000061a00003d888, obj=0x00006100000c8b48, dir=5, range=13, shots=1, archery=true, radiance=false) at player-attack.c:1185:27
2. do_cmd_fire(cmd=0x0000000100beadc0) at player-attack.c:1543:2
3. process_command(ctx=CTX_GAME, cmd=0x0000000100beadc0) at cmd-core.c:276:3
4. cmdq_pop(c=CTX_GAME) at cmd-core.c:305:2
5. process_player at game-world.c:876:8
6. run_game_loop at game-world.c:980:3
7. play_game(mode=GAME_LOAD) at ui-game.c:932:4

At the point of the crash, path_n was 0, grid was (x = 66, y = 22), target was (x = 66, y = 22), and range was 13.  I had attempted to shoot the spider hatchling at the south-southeast knight's move in the attached screen shot, but when that didn't seem to work (perhaps already crashing or something else...) I pressed escape a handful of times before realizing the game had crashed.

<img width="916" alt="ranged_helper_path_n_is_0_crash" src="https://github.com/NickMcConnell/NarSil/assets/55062581/8a2d2546-3609-48da-a5cd-614bb65a369a">

**Comment by NickMcConnell** [comment]
I'm going to close this soon if there are no problems (although I haven't really tested it thoroughly).

**Comment by NickMcConnell** [comment]
OK, I'm calling this fixed.
