### ISSUE TITLE
Update of sidebar evasion

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#198]
Equipping a set of gauntlets of swordplay (their type of enchantment was not none at time I equipped them) with a sword also equipped changed the evasion score shown on the character sheet, but the evasion score shown on the side bar remained at the value prior to using the gauntlets until I changed levels.

**Comment by NickMcConnell** [comment]
Right, this is something I hoped I had fixed in #144

**Comment by backwardsEric** [comment]
I'm seeing that the call to update_player_knowledge() in update_stuff() can trigger a call to redraw_stuff() (via player_know_object()->player_exp_gain()->check_experience()).  That redraws with the old player state since the new player state hasn't been copied over yet.  Moving the copying of the state to before the call to update_player_knowledge() would avoid that.

It isn't yet clear to me why the experience gain hadn't happened in the call to ident_on_wield().  The update_stuff() call that triggers the experience gain is the one at the end of inven_wield() after ident_on_wield() has been called.
