### ISSUE TITLE
Floor object weight display

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#207]
In Sil 1.3, a weapon or piece of armor at the character's feet gets a message like this which displays the weight, "You see a Curved Sword (-1,2d5) [+1] 4.0 lb.".  In NarSil as of 20bc3b09bd34fe802c463f0797cf13495f3eceba , the message is like this, "You see a Curved Sword (-1,2d5) [+1].", and doesn't display the weight.

**Comment by NickMcConnell** [comment]
Yep, that's important for Sil

**Comment by backwardsEric** [comment]
In SIl 1.3, it doesn't display the weight of arrows at the feet of the character.  With the changes in https://github.com/NickMcConnell/NarSil/commit/d451eb28dc68146de148660f0ec36fd63b48f5b4 , NarSil does display the weight of arrows.
