### ISSUE TITLE
Infinite loop in choose_ranged_attack() for full AI

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#211]
Using 13fa6b6b00d48290c23c9bf69b231b9c507a5283 compiled from source on macOS with OPT="-O0 -g -DUSE_STATS", I encountered what appears to be an infinite loop when being attacked by an Easterling spy.  Attaching with the debugger to the process indicated it was in the full AI loop in choose_ranged_attack().  Stepping into the loop increment (i.e. the call to rsf_next()) gave this call stack:

1. 0x000000010cb77500 narsil`flag_next(flags="\U00000001\U00000001", size=3, flag=1) at z-bitflag.c:78:17
2. 0x000000010caab101 narsil`choose_ranged_attack(mon=0x00007f85d715d6c8) at mon-attack.c:131:40
3. 0x000000010caaadbf narsil`make_ranged_attack(mon=0x00007f85d715d6c8) at mon-attack.c:190:15
4. 0x000000010cabfdbd narsil`monster_turn(mon=0x00007f85d715d6c8) at mon-move.c:3374:52
5. 0x000000010cabf166 narsil`process_monsters(minimum_energy=0) at mon-move.c:3719:3
6. 0x000000010ca95384 narsil`run_game_loop at game-world.c:1002:4
7. 0x000000010cb3790c narsil`play_game(mode=GAME_LOAD) at ui-game.c:932:4

The loop index stays at 1 after the call to rsf_next() returns.  Shouldn't mon-attack.c:131 be
```for (i = FLAG_START; i < RSF_MAX; i = rsf_next(mon->race->spell_flags, i + 1)) {``` instead of what it is now?

**Comment by NickMcConnell** [comment]
Almost certainly, I've been already corrected at least two of these loops that I did wrong.  I can't check currently as my dev VM is horribly broken.
