### ISSUE TITLE
Poison resistance to monster attack working correctly?

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#222]
With 7f79670b9dea54f02fa4f62b903fefc146c5dfe5 (macOS compiled from source, OPT="-O0 -g -DUSE_STATS -fsanitize=address -fsanitize=undefined"), a character had an unidentified leather armor of Venom's end equipped but still ended up badly poisoned by spider hatchlings.  In melee_effect_handler_POISON() the call to player_inc_timed() doesn't check for resistance.  Is that right? ~Also the logic for elem_bonus() in mon-attack.c looks suspicious (though it is the same logic as in Sil 1.3):  a resistance level of 1 would trigger a bonus die (the same as a resistance level of -1) but a resistance level of zero would not.  I haven't checked the Sil manual, but shouldn't the "if (resistance == 1)" line be "if (resistance == 0)" and the "if (resistance < 0) return (-resistance);" line be "if (resistance < 0) return (1-resistance);"?~ (since the resistance levels are 1 for no resistance, > 2 for some amount of resistance, and -2 for a vulnerability, the logic in elem_bonus() looks to be correct)

Also, I don't remember those attacks by the spider hatchlings causing the armor to be identified.  I'm not sure if the armor would have been identified in Sil 1.3 under similar circumstances.

**Comment by NickMcConnell** [comment]
That looks wrong, I'll have to check
