### ISSUE TITLE
Lag for indication of stealth mode

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#226]
In 7f79670b9dea54f02fa4f62b903fefc146c5dfe5 , toggling stealth mode changes what is displayed on screen when the player's current turn elapses (so after a command that takes energy).  In Sil 1.3, the feedback for toggling stealth mode is immediate:  the 'Stealth' indicator appears or disappears when 'S' is pressed without needing another command that takes energy.

Personally, I like Sil 1.3's immediate feedback.

**Comment by NickMcConnell** [comment]
Agreed
