### ISSUE TITLE
Examine item reveals information about unknown slays

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#227]
With 7f79670b9dea54f02fa4f62b903fefc146c5dfe5 (compiled from source on macOS; OPT was "-g -O0 -fsanitize=address -fsanitize=undefined"), examining an unidentified {special} broken sword says 

```
a Broken Sword (-2,1d5) {special}
Found lying on the floor at 50 feet

You do not know the full extent of this item's powers.
Slays undead.
Can be destroyed by acid.
```

. Shouldn't that slay information be hidden until the weapon is identified? I've attached the save file where that broken sword is in the pack.

It also happens for the unidentified shortsword of Gondolin in the tutorial where examining it says

```
a Shortsword (+0,1d7) [+1] {special}
Found lying on the floor at 50 feet

You do not now the full extent of this item's powers.
Slays trolls, orcs.
Can be destroyed by acid.
```
[Osserch.zip](https://github.com/NickMcConnell/NarSil/files/11782476/Osserch.zip)

**Comment by NickMcConnell** [comment]
Looks like a bug
