### ISSUE TITLE
The in-game save file selector displays useless character level information

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#228]
With 7f79670b9dea54f02fa4f62b903fefc146c5dfe5 (compiled from source on macOS; OPT was "-g -O0 -DUSE_STATS -fsanitize=address -fsanitize=undefined"), the in-game save file selector (one way to get to that with the Mac or Windows front end is to start the tutorial and use 'Q' to kill off the tutorial character; with a version that uses main.c, the '-c' command line option displays the save file selector at startup) includes a meaningless character level for existing save files:  for instance, the "L0" in "Use Osserch: Osserch, L0 Noldor House of Feanor, at DL1".  Could drop that character level entirely (so that example would be "Use Osserch: Osserch, Noldor House of Feanor, at DL1") or replace it with the total experience (that wouldn't be particularly useful for a save file if Sil-q's "Fixed XP" birth option is implemented and the savefile used that option).

**Comment by NickMcConnell** [comment]
Seems sensible.  You wrote that code, right?

**Comment by backwardsEric** [comment]
Yes.  It's pulling the description section from the savefile for what appears after the colon.  Is there any interaction between that description section and the ladder/competition handling on http://angband.oook.cz?

**Comment by NickMcConnell** [comment]
No, the ladder goes off character dump info only.
