### ISSUE TITLE
macOS:  double clicking on save file in the Finder doesn't open it in NarSil

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#238]
As of fe4424e0f5a897c20b4db30fdb8dd95b72b52ca5 , double clicking on the save file doesn't open it in NarSil.  If Angband has been used on the system, it tries to open it in Angband.

The solution could be similar to what was done for FAangband:  change the four byte code used for FTYPE_SAVE in src/main-cocoa.m's cocoa_file_open_hook() to something else that hopefully won't clash with some other file type code and change the "SAVE" at line 48 of src/cocoa/NarSil-Cocoa.xml to match that chosen four byte code.  May also want to the definition of ANGBAND_CREATOR in main-cocoa.m to be a four-byte code that isn't the same as what Angband uses.  Sil 1.3 and Sil-q have 'Sil1' for the creator code, but since neither have a hook in the core to call out to a front end when a file is created,  that creator code isn't used in practice.

**Comment by NickMcConnell** [comment]
I think changing the code and leaving the creator code as is is fine.
