### ISSUE TITLE
Sidebar update after choosing the parry ability

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#243]
With ea741154342ced68a2c0d58d5364fa01baf491cb (compiled from source on macOS; OPT was "-g -O0 -DUSE_STATS"), a character had an evasion of 10, according to the sidebar display, and a Curved Sword (-1,2d5) [+1] equipped.  The character then took the Parry ability.  The amount of evasion shown on the side bar was still 10 but then updated to 11 after the character moved.

I haven't checked Sil 1.3's behavior for this, but my preference would be for the sidebar value to be correct after coming out of the ability selection.

**Comment by NickMcConnell** [comment]
Yes, agreed.  Related to #198 maybe?

**Comment by backwardsEric** [comment]
Sil 1.3 immediately updates the sidebar but, if the ability was added via the character sheet, that's not updated after exiting the ability selection (that also happens in NarSil).

This bug is likely localized to player_gain_ability() (though handling the update problem for the character sheet would be where do_cmd_abilities() is called in do_cmd_change_name()).  #198 didn't involve player_gain_ability().
