### ISSUE TITLE
Instance of poorly ordered messages

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#248]
With abbff091d19b576cfccb0fabd29e5153544171e0 +  https://github.com/NickMcConnell/NarSil/pull/247 (compiled from source on macOS; OPT was "-g -O0 -DUSE_STATS -fsanitize=address -fsanitize=undefined"), had a character step on a hidden caltrop and got these messages:

```
You have found a trap.
You step on a caltrop.
You die.
It pierces your foot.
You feel yourself moving slower!
```

It'd be better if the last two appeared before "You die." or did not appear at all.

**Comment by NickMcConnell** [comment]
I'm going to start putting things like this into post-1.3.0, as I want to get 1.3.0 actually out soonish so I can start building Beleriand on it.  Note that this assumes I'm actually spending some time working on at least one of these games, which is currently barely happening...

**Comment by backwardsEric** [comment]
Okay.  There's a somewhat related issue for this one that you may want to think about for matching Sil 1.3:  why do caltrops increase SLOW twice (one with the chance of resistance, the other without).  If I've read the Sil 1.3 implementation in cmd1.c correctly, the equivalent effect in NarSil would be TIMED_INC_CHECK:SLOW with a dice of 4d4.

**Comment by NickMcConnell** [comment]
It actually only slows once - the TIMED_INC_CHECK line purely does the check and passes it to decide whether to do the extra effect (which is why that has no resistance).  The reason it's done like this is to allow the "It pierces your foot" message.
