### ISSUE TITLE
Bug: Object Bonuses

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#25]
"You see a Brass Lantern (3000 turns) (+1) [+1,1d1]."

Lights shouldn't ever have ACC, EV, or PROT, as far as I can remember.

EDIT: Found a (+1,3d5) [+1,1d1] throwing axe; pretty much all of that is more number than it should have.

**Comment by NickMcConnell** [comment]
Done, I believe.
