### ISSUE TITLE
Birth screen: finish with random choices

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#256]
With bb10a024393cf56492b99e95f12062c258ac8007 (compiled from source on macOS; OPT was "-O0 -g -DUSE_STATS -fsanitize=address -fsanitize=undefined"), pressing '@' while at the race selection menu has at least two issues:

1. Invalid combinations of race and house can occur.  I saw Noldor/Haldor for one character.
2. None of the 13 available points for buying stats are used.  No skills are bought as well, but that can be done once the game starts.

Could get rid of the '@' option entirely though it's nice to have something quick to get a plausible character.  Could have '@' randomly fill out the what's left of race, class, and sex if it's pressed before getting to the stage of buying stats and then have the player finish off the character manually for the statistics, skills, name, and history though that means that '@' isn't a quick way to get a plausible character.  Could add plausible sets of stat buys for each house to house.txt and choose one of those at random when '@' is pressed.

**Comment by NickMcConnell** [comment]
My immediate reaction is just kill it.  Maybe it's a good idea to have a set of plausible starting builds to choose from, but on the other hand maybe it's best to emphasise to players straight away that these choices matter.  I think this needs some thought.
