### ISSUE TITLE
Birth screen: random house choice

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#257]
With https://github.com/NickMcConnell/NarSil/commit/bb10a024393cf56492b99e95f12062c258ac8007 (compiled from source on macOS; OPT was "-O0 -g -DUSE_STATS -fsanitize=address -fsanitize=undefined"), pressing '*' while in the house menu doesn't seem, from what's presented on the screen, to produce a random choice as it does with the race and sex menus, instead it seems to be choose what was previously selected.  Tracing execution with the debugger, it looks like the house in the global player is randomly set, but that what's displayed doesn't reflect that because the house menu is regenerated.

**Comment by NickMcConnell** [comment]
I guess this depends on what happens with #256.

**Comment by backwardsEric** [comment]
It is somewhat independent of that one - unless your thinking for #256 is to kill the '*' key along with '@' one.  Sil 1.3 does have '*' for the race and house menus to choose one at random.

**Comment by NickMcConnell** [comment]
Ah, OK.
