### ISSUE TITLE
Running leaking information?

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#265]
I've seen instances where running down a corridor stops for no apparent reason.  Then stepping in the direction in which I was running reveals a monster that was just beyond the light radius at the point the run stopped.  Is the running stopping one grid too early and thus leaking information to the player?  I haven't checked this in Sil 1.3 closely enough to know if it behaves differently.  From what I recall, none of the characters had the Listen ability if that would have some impact on this.

The attached savefile is an example.  I had run from the room to the south, and the run stopped at the current location of the character in the savefile.  Stepping one grid to the right from that location revealed a wolf in the corridor.

[Osserch.zip](https://github.com/NickMcConnell/NarSil/files/11924357/Osserch.zip)

**Comment by NickMcConnell** [comment]
Another possibility is that the run stopped on seeing the wolf, and then the wolf (being faster and having random movement) took a step back.  That's hard to check though.

**Comment by backwardsEric** [comment]
Yes, that's possible the wolf is unwary and not asleep.  It's alertness is -10, skip_next_turn and skip_this_turn are 0, mflag is MFLAG_HANDLED, encountered is 0, wandering_dist is 0, min_range and best_range are 0, consecutive_attacks is 0, turns_stationary is 0, and previous action is { 0, 0, 0, 0, 0 }.

**Comment by NickMcConnell** [comment]
I think I'm just going to assume this is not a bug, as I'm unaware of any other evidence of it.
