### ISSUE TITLE
Wolves not surrounding?

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#268]
The second part of the tutorial has the player use the song of slaying to deal with several wolves.  In NarSil, if the player retreats to just inside the room before the wolves like this,

```
C#.
CC@
C#.
```

, I haven't seen the wolves try to surround the player.  Then the player only has to deal with one at a time: the one in the doorway.  In Sil, the wolf closest to player seems more willing to move into the room with the player allowing multiple wolves to attack the player at the same time.

**Comment by NickMcConnell** [comment]
This at least warrants some checking.

**Comment by backwardsEric** [comment]
From a brief examination of Sil 1.3 in the debugger, the wolf I saw getting into the room was the one in the doorway making an erratic move.  I see one difference between NarSil's and Sil 1.3's logic for the erratic moves (thus https://github.com/NickMcConnell/NarSil/pull/272 ), but I don't know if that makes an impact on the behavior seen with this issue.

**Comment by backwardsEric** [comment]
From what I've seen, #272 was sufficient to get the wolves moving into the room with the player so I'd mark this issue as resolved.
