### ISSUE TITLE
hjkl movement option issues

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#269]
Using 982a5b6aa5db70378f3000339f1264145d64e337 compiled from source on macOS (OPT was "-g -O0 -DUSE_STATS -fsanitize=address -fsanitize=undefined"), I saw the following problems with the hjkl option:

1. The keys that ui-game.c lists for "destroy an item", "look around", "use an item", "bash a door", and "repeat previous command" in that mode do not seem to work as advertised.  In the Sil keyset, control-k, control-l, control-u, control-b, control-n (or ^k, ^l, ^u, ^b, ^n) all give the "Type '?' for help." message.  In the Angband keyset, they're intercepted by the keymaps for control+movement key.
2. Using ',' to try run (as listed in ui-game.c) when that option is enabled does not work.  With the Sil keyset, it asks for a direction but the command executed seems to be alter the grid in that direction rather than run.  In the Angband keyset, it gives the "Type '?' for help." message.  For the Sil keyset, keeping the run command on '.' when the hjkl option is on seems a better choice to me (not trying to emulate how running works with the roguelike keys in Angband; the Angband keyset + hjkl option does that).
3. Putting tunneling on control-t when that option is on, at least for the Sil keyset, doesn't make much sense since 'T' is available and does not conflict with any of the movement keys.  For the Angband keyset it perhaps does make sense for emulating how the roguelike keyset works in Angband.
4. The "fire at nearest target" ('h' in all keysets) command gets intercepted by the keymap for moving right when that option is on.
5. The "toggle ignoring of items" ('K' in all keysets) command gets intercepted by the shift+k keymap when the that option is on.
6. When that option is on, according to the keys listed in ui-game.c,  "center map" and "look around" use the same key.

**Comment by NickMcConnell** [comment]
Thanks for this.  I'm currently working on #137, and at the same time making sure that all the commands line up with that help, and work.  There will be a few changes ('K' for unignoring is going to change, for example).

**Comment by NickMcConnell** [comment]
Well, I *was* working on #137, but have had significant computer issues this week and have probably lost all the changes, along with my entire dev environment.  Delays should be expected.

**Comment by bridgesense** [comment]
I've been getting around using pullup menu, but I'm looking forward to the hjkl update.

**Comment by backwardsEric** [comment]
If it helps, the draft of what I was working on for the in-game help before I realized you had started in on it is here, https://github.com/backwardsEric/NarSil/tree/help .

**Comment by NickMcConnell** [comment]
> If it helps, the draft of what I was working on for the in-game help before I realized you had started in on it is here, https://github.com/backwardsEric/NarSil/tree/help .

Thanks, I'm hoping to be functional again soon and will have a look.

**Comment by backwardsEric** [comment]
https://github.com/NickMcConnell/NarSil/pull/320 fixes most of (1) in my hands: control-l still does not work right because of (6).  The behavior in (2) is because there is a keymap which maps ',' to alter the player's grid.  Leaving that keymap as is to match Sil seems like the right option to me.  Some code changes for how altering works seem to be needed to get that keymap to work since it rejects 5 as a direction and asks for a new one (directly entering '/' + '5' does work however).

**Comment by backwardsEric** [comment]
https://github.com/NickMcConnell/NarSil/pull/321 gets the keymaps for '^Z' and ',' working to alter the player's grid:  so (2) in the original post can now be dismissed as "working as expected: ',' alters the player's current grid".

**Comment by backwardsEric** [comment]
https://github.com/NickMcConnell/NarSil/pull/318 moved tunneling to 'T' in all the key sets so '^T' was available for automatic throwing.  That makes (3) a moot point.

**Comment by NickMcConnell** [comment]
As far as I can see, there's no way to get the general use command in Sil 1.3.0 with the Angband-like keyset and hjkl movement (I posted to the forum about it), so I guess we just keep that as ^u (which I guess was my original plan, and I have just wasted time thinking about this at all...)

**Comment by NickMcConnell** [comment]
I think everything but (4) is fixed now.
