### ISSUE TITLE
Monster random move chance when adjacent to the player

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#273]
In NarSil as of 982a5b6aa5db70378f3000339f1264145d64e337 , the logic for modifying the chance of a monster's innate random move based on proximity to the player is

```
        if (mon->cdis > 1) {
                chance /= 2;
        }
```

(see monster_turn_random_move() in mon-move.c).  That is the same as in Sil 1.3 (melee2.c:4719-4722) and Sil-q 1.5 (melee2.c:5184-5187), but all seem to do the opposite of what they say they want: increasing the chance that the monster attacks the player when the monster is next to the player.  One solution would be

```
        if (mon->cdis == 1) {
                chance /= 2;
        }
```

**Comment by NickMcConnell** [comment]
Agreed.
