### ISSUE TITLE
KILL_BODY flag

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#283]
As of 982a5b6aa5db70378f3000339f1264145d64e337 , NarSil still has the KILL_BODY flag for monster races, but the supporting logic for it (in mon-move.c's monster_entry_chance() and process_move()) is not there.  That does not matter for matching Sil 1.3 as neither it nor NarSil have any monsters that use the KILL_BODY flag.  To prepare for changes after matching Sil 1.3, need to decide whether to remove the KILL_BODY flag entirely or add back the logic necessary to support it.

**Comment by NickMcConnell** [comment]
I think probably it can come out, but I'll think about it.

**Comment by NickMcConnell** [comment]
Yep, it can go.
