### ISSUE TITLE
Accumulation of randart files

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#289]
Killing off a lot of characters in NarSil leads to an accumulation of randart_*.txt files in the archive subdirectory where the user's files for NarSil are stored.  From what I've seen, those files are small (62 bytes each) so space may be less of an issue than the number of files.

If the randart file was only generated when needed (player gets the artifice skill from the smithing tree?), that would reduce the potential impact.

**Comment by NickMcConnell** [comment]
That's a good thought
