### ISSUE TITLE
Bug: 100' Forge Generation

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#30]
100' did not spawn its supposed-to-be-guaranteed forge for me; either a problem with the specialcase for 100' specifically, or with forge generation in general.

EDIT: Found a forge on a deeper level; it was probably a problem with the 100' specialcase.

**Comment by NickMcConnell** [comment]
I'm pretty sure guaranteed forges are a Sil-q thing only.

**Comment by ThatGitMITZE** [comment]
Strictly they're not; Sil-V has exactly 1 (one) at 100'. Sil-Q has more, though I don't remember what all depths they are there.

**Comment by NickMcConnell** [comment]
Are you sure?  I can't find any reference to it in the code for Sil 1.3.0.

**Comment by ThatGitMITZE** [comment]
I was pretty positive, but just to make sure I did a couple of test games of Sil-V; three out of three 100's had a forge on them.

**Comment by NickMcConnell** [comment]
Well, I've asked the [peanut gallery](http://angband.oook.cz/forum/showpost.php?p=160480&postcount=22).

**Comment by NickMcConnell** [comment]
OK, you're right - I've found how it's done.

**Comment by NickMcConnell** [comment]
Looks like this is related to #64.

**Comment by NickMcConnell** [comment]
Calling this done now.
