### ISSUE TITLE
SCARE spell for monsters: differences from Sil 1.3

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#302]
From Sil's version in melee1.c:2141-2160:

1. If the caster is seen, there's a 50% chance they use the noisy version of the spell.  NarSil uses the noisy version only when the caster is unseen.
2. The noisy version looks like it has the same side effect as the NOISE effect with a dice of -10 in NarSil.  NarSil doesn't have that side effect.
3. The fear can be resisted.  NarSil uses TIMED_INC_NO_RES for the fear so there's no chance to resist it.

**Comment by NickMcConnell** [comment]
I think that fixes all the issues, and also makes the CONF and SLOW spells work correctly.  SCREECH is still not perfect, but only in terms of one message so I don't think I care.
