### ISSUE TITLE
Random character generation creates impossible combinations

### ISSUE THREAD

**Issue by Karcharoth** [NickMcConnell/NarSil#304]
The @ key will generate your character with random choices, allowing a Noldo of Haleth's House. It could be removed or, if desirable, it could move you forward 1 step in character generation, e.g. select Noldor -> press @ -> game randomly selects Finarfin. Or it could just move forward multiple times in character generation.

**Comment by NickMcConnell** [comment]
Did #258 and/or #259 fix this?
