### ISSUE TITLE
Bug: Wielding Arrows

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#31]
Trying to wield a stack of arrows has you put them into your quiver one at a time, making you do the command sequence for each.

**Comment by ThatGitMITZE** [comment]
Unsure whether to file under this or #42, but quivering isn't quite fixed; found a bunch of arrows, wielded them, except now they're in both my quiver and my inventory. Doing it again with the other quiver slot and now I have the same stack three times, in both quiver slots and in my inventory.

**Comment by NickMcConnell** [comment]
Yes, I had already noticed arrows appearing in two places, but assumed it was purely an interface issue.  Which it may be, but it still needs fixing.
