### ISSUE TITLE
Crash on opening small steel chast with poison trap

### ISSUE THREAD

**Issue by NickMcConnell** [NickMcConnell/NarSil#311]
" twice now I have found a small steel chest, and when I open it a noxious vapor escapes, my game crashes, and my panic save has 300 more xp afterwards
testing with debug commands, it seems only small steel chests with noxious vapor traps crash" - Karkaroth on discord

**Comment by backwardsEric** [comment]
Jumping to 300 feet, creating a steel chest with the debugging commands, and then opening it led to a crash accessing a NULL pointer (this was done on macOS with 95a4e2882ee4b7c8c73b51fbec4bd3b1bbe50e44 compiled from source; OPT was set to "-g -O0 -DUSE_STATS -fsanitize=address -fsanitize=undefined").  The call stack at the point of the crash was:

1. update_combat_rolls_attack(type=EVENT_COMBAT_ATTACK, data=0x00007ff7bfef88e0, user=0x0000000000000000) at ui-combat.c:135:58
2. game_event_dispatch(type=EVENT_COMBAT_ATTACK, data=0x00007ff7bfef88e0) at game-event.c:43:3
3. event_signal_combat_attack(type=EVENT_COMBAT_ATTACK, attacker=source @ 0x00007ff7bfef8930, defender=source @ 0x00007ff7bfef8920, vis=true, att=-1, att_roll=-1, evn=-1, evn_roll=-1, melee=false) at game-event.c:333:2
4. project_p(origin=source @ 0x00007ff7bfef89a0, grid=(x = 7, y = 22), dd=10, ds=4, typ=3) at project-player.c:420:3
5. project(origin=source @ 0x00007ff7bfef8f40, rad=0, finish=(x = 7, y = 22), dd=10, ds=4, dif=0, typ=3, flg=512, degrees_of_arc=0, uniform=true, obj=0x0000000000000000) at project.c:1009:8
6. effect_handler_SPOT(context=0x00007ff7bfefc700) at effect-handler-attack.c:737:6
7. effect_do(effect=0x00006060000b1208, origin=source @ 0x00007ff7bfefc6c0, obj=0x0000610000048448, ident=0x00007ff7bfefcaa0, aware=false, dir=5, cmd=0x0000000000000000) at effects.c:378:16
8. chest_trap(obj=0x0000610000048448) at obj-chest.c:529:6
9. do_cmd_open_chest(grid=(x = 7, y = 22), obj=0x0000610000048448) at obj-chest.c:612:3
10. do_cmd_open(cmd=0x00000001009beab0) at cmd-cave.c:493:10
11. process_command(ctx=CTX_GAME, cmd=0x00000001009beab0) at cmd-core.c:276:3
12. cmdq_pop(c=CTX_GAME) at cmd-core.c:305:2
13. process_player at game-world.c:879:8
14. run_game_loop at game-world.c:1065:5
15. play_game(mode=GAME_LOAD) at ui-game.c:932:4

At the point of the crash, attacker.what is SRC_CHEST_TRAP, vis is true, race1 is NULL, combat_number is zero.
