### ISSUE TITLE
Crash: [e]quipment

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#32]
Just tried to check [e]quipment after discovering the wield-from-floor bug; it caused a crash.

EDIT: Panic save worked, doing the same action again did not cause the crash again.
EDIT: Seems to happen from wielding an a single arrow (because you can't wield a stack currently), and then checking [e]quipment afterwards.

**Comment by NickMcConnell** [comment]
I believe this is fixed, so I'll close it.
