### ISSUE TITLE
Effect of temporary stat boost potions

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#322]
According to the Sil 1.3 source code (use-obj.c:277-315), a temporary stat boost potion will apply the temporary boost if the current stat is not drained by 3 or more. When the stat is drained by 3 or more, the potion restores up to 3 points. That's different than what NarSil is doing (always restoring and always applying the temporary boost), though NarSil's behavior better matches the descriptions for the potions. Sil-q's code looks the same as in Sil 1.3 for those potions.

Split off from https://github.com/NickMcConnell/NarSil/issues/90 .

**Comment by NickMcConnell** [comment]
Great, thanks

**Comment by NickMcConnell** [comment]
OK, I'm going to keep this as is - I don't think it's a huge game-breaking distinction from the Sil behaviour.
