### ISSUE TITLE
OpenBSD: alignment warnings when using Makefile.std and clang

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#326]
On OpenBSD 7.3 (32-bit if it matters) using Makefile.std but with CC changed to be "cc" rather than "gcc", I get the following warnings:

```
cave-fire.c:1162:14: warning: cast from 'uint8_t *' (aka 'unsigned char*') to 'int16_t *' (aka 'short *') increases required alignment from 1 to 2 [-Wcast-align]

z-virt.c:47:2: warning: cast from 'char *' to 'size_t * (aka unsigned long *') increases required alignment from 1 to 4 [-Wcast-align]

z-virt.c:66:19: warning: cast from 'char *' to 'size_t * (aka unsigned long *') increases required alignment from 1 to 4 [-Wcast-align]
        memset(p, 0xCD, SZ(p));

z-virt.c:82:2: warning: cast from 'char *' to 'size_t * (aka unsigned long *') increases required alignment from 1 to 4 [-Wcast-align]
```

Adopting Elly's patch to Vanilla which dropped memory poisoning would remove the last three warnings.

**Comment by backwardsEric** [comment]
For the first warning, it looks that line could be rewritten to avoid the warning like this:

```
    g = g0 + point->grid[octant];
```

**Comment by NickMcConnell** [comment]
Yes, that code is *very* old and is almost certainly using unnecessary memory location manipulations.

**Comment by NickMcConnell** [comment]
OK funny story, I just looked at the z-virt.c errors, then compared the code with Vanilla, the tracked down where that had changed, then cherry-picked Elly's fix in, *then* read the last line of your first comment...
