### ISSUE TITLE
Missing save and panic folders?

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/NarSil#327]
I got error messages on startup saying missing user/save and then missing user/panic. Fixed by creating the folders in terminal. Don't know if some quirk on my PC or not.

**Comment by NickMcConnell** [comment]
Windows, I assume?  Those folders seem to be there fine for me.

**Comment by davidk64fnq** [comment]
I downloaded again (Windows) and yes they were there for me as well! Odd.
