### ISSUE TITLE
Noticing the sword is more effective against orcs in tutorial

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/NarSil#329]
I'm not sure how I see the sword is glowing when wielded against orcs? I did get a message identifying it during the combat but the glowing observation is before that?

**Comment by NickMcConnell** [comment]
Will check

**Comment by backwardsEric** [comment]
You should see a increase in the light radius when wielding a Gondolin weapon and an orc is nearby (I see that in the tutorial but it can be easy to miss).  It might be nice if the equipment or pack listing would show the weapon in light blue when the condition for glowing is met, but Sil 1.3 does not.

**Comment by NickMcConnell** [comment]
I see it in the tutorial too.  I think I kind of like leaving it as something you'll notice if you're paying attention.
