### ISSUE TITLE
Morale question

### ISSUE THREAD

**Issue by davidk64fnq** [NickMcConnell/NarSil#331]
![image](https://github.com/NickMcConnell/NarSil/assets/63939880/2fcd649a-29d1-44f0-9551-889105de9f84)
Still not understanding morale. The orc shown fled from combat a few turns prior into room above and now has returned. I know he gets +6 at some point for stopping fleeing but how can he now be a 9 when his health is < 50% which incurs a -4 penalty?

**Comment by NickMcConnell** [comment]
It's possible that it got a 'failed to escape' boost at some point.  It's hard to tell what's happened here - I'll do some checking.

**Comment by davidk64fnq** [comment]
If I was to guess I'd say it's to do with getting +6 for stopping fleeing. The orc takes some damage and flees into next room where the damage starts healing and the fleeing -6 starts decaying to the point where stop fleeing is triggered and then the +6 for stopping takes him over his normal full morale value. It might be the code is fine but a debate as to whether stopping fleeing should give +6 to morale. Maybe a RFC to remove the +6 modifier?

**Comment by NickMcConnell** [comment]
OK, I've checked, and it all makes sense - note that there's also a -2 penalty for hurt and already fleeing, which gets applied early on but then stops when the orc is back to 75% health.

As for changing the morale system, I think it's pretty finely tuned already.
