### ISSUE TITLE
Misleading staff of summoning description

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#336]
The staff of summoning description, "It summons 1d4 monsters out of sight on the current level.", is better than Sil 1.3's, "It summons 2d4 monsters out of sight on the current level.", in that it correctly states the number of monsters summoned, but a summoned monster can be in sight if the stairs it appears on is in sight.  Perhaps use Sil-q's description (edit: this is from Sil-q 1.5), "It summons monsters to the stairs on the current level."?

**Comment by NickMcConnell** [comment]
Agreed
