### ISSUE TITLE
Bug: Lighting Mechanics

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#35]
Found a Brass Lantern of Brightness (the lantern mentioned in #25 actually), which in Sil would illuminate a radius of 3; it only appears to do 2 here.

**Comment by ThatGitMITZE** [comment]
I feel like the problem here is with lights as a whole, not just ego/lanterns; looking at a lesser jewel in the smithing menu I get no info whatsoever aside from the name and weight, lanterns have intensity 2, and feanorian lamps have 3. Also, amulets of the blessed realm don't say anything about giving permanent light (which they did in Sil-V).

Maybe I'm misremembering how intensity is supposed to work, but I thought it basically started with the player's square (e.g. intensity 1 just lights the player's square, intensity 2 is radius 1 light, intensity 3 is radius 2 light, etc.); it seems to be off-by-one from that here though.

**Comment by NickMcConnell** [comment]
I haven't checked this, but also smithing menu info may not be complete.

**Comment by NickMcConnell** [comment]
There does appear to be some weirdness with light, but I haven't managed to track it down yet - the code all looks to be using the same logic as in Sil.

**Comment by davidk64fnq** [comment]
> I feel like the problem here is with lights as a whole, not just ego/lanterns; looking at a lesser jewel in the smithing menu I get no info whatsoever aside from the name and weight, lanterns have intensity 2, and feanorian lamps have 3. Also, amulets of the blessed realm don't say anything about giving permanent light (which they did in Sil-V).
> 
> Maybe I'm misremembering how intensity is supposed to work, but I thought it basically started with the player's square (e.g. intensity 1 just lights the player's square, intensity 2 is radius 1 light, intensity 3 is radius 2 light, etc.); it seems to be off-by-one from that here though.

Looked through 1.5 manual to see what it says about light radius vs intensity. Page 37 describes inner light ability which seems to say they are two different things rather than both being radius but with different reference points? There is no mention of intensity at all but plenty of level - maybe level is intensity and level is distinct from radius.

**Comment by ThatGitMITZE** [comment]
Radius is radius, intensity is essentially how strong or bright your light is within that radius. Like, say you have radius 3 light, the player's row would look something like this:

123@321

where @ is the player and the numbers represent the nearby tiles in the row being lit up with X intensity (note that the light gets weaker the further away from you it is).

Now, say you have Inner Light, and Inner Light is +1 intensity. It would turn the above example into:

234@432

Now, things also produce unlight, which to my understanding basically works the same way as above, except with negative numbers, and at any given time a square takes into account all sources of light and unlight shining on it, and whether the sum total is above 0 or not changes whether the square is lit. In Sil (note, that this is a SIL codebase rewrite, not a SIL-Q codebase rewrite, and in this instance this is an important distinction), multiple difference sources of light can stack together, so that say, an object on the floor underneath you giving off light (this is something that's been removed in Sil-Q, to my knowledge), gives you effective additional light intensity for the radius of light it gives off (I forget whether it's 1 tile or two tiles or dependant on the exact object).

**Comment by NickMcConnell** [comment]
I believe this is done now, if not we can open a new issue.
