### ISSUE TITLE
Opportunist: player/monster symmetry for fleeing by stairs

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#363]
From looking at the code, the player's Opportunist ability can trigger when a monster leaves via the stairs, but a monster's Opportunist ability does not trigger when the player leaves via a staircase.  Sil 1.3's behavior (from looking at the code) seems to be the same in that regard.

If there's interest in making the rules as symmetric as possible for monsters and players, that's one instance of a missing symmetry.

**Comment by NickMcConnell** [comment]
OK, this is a future one, then

**Comment by NickMcConnell** [comment]
This also triggers Zone of Control in the same circumstances.  Note that precisely one monster actually has Opportunist, and none have Zone of Control 😄
