### ISSUE TITLE
Bug: Hunger Display

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#38]
When you're actually hungry the game displays your satiation percentage at the bottom; when you're not, there's no display for it at all.

**Comment by NickMcConnell** [comment]
I'm undecided whether to put this in as in Angband or leave it out as in Sil.

**Comment by ThatGitMITZE** [comment]
Whatever you do, make it consistent; currently the how informative the display is depends on whether you're hungry or not.
