### ISSUE TITLE
Hardiness not boosting protection as Sil 1.3 does

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#381]
From looking at the code, NarSil (combat.c:703) boosts the protection like this if the Hardiness ability is active:

`prt += damcalc(1, MIN(1, p->state.skill_use[SKILL_WILL] / 6), prot_aspect);`

While Sil 1.3 has (melee1.c:94):

`prt += damroll(1, p_ptr->skill_use[S_WIL] / 6);`

**Comment by NickMcConnell** [comment]
That's a really odd mistake to make, I must have been confused by the other calculations in that function.
