### ISSUE TITLE
Bug: Enemy AI

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#39]
Enemies don't seem to act like they're supposed to, for things that would behave "smarter" or have otherwise different ways of approaching the player; orc scouts currently engage in melee where they're supposed to try and keep sight on you but at distance, orc soldiers will follow you blindly into hallways, etc.

**Comment by NickMcConnell** [comment]
My current suspicion is that monsters are not becoming aware quickly enough, but this stuff is kind of hard to confirm.

**Comment by ThatGitMITZE** [comment]
Paying closer attention, I am reasonably certain that yes, things are not detecting the player as quickly as they do in Sil.

**Comment by backwardsEric** [comment]
With regards to the monsters not becoming aware quickly enough, Sil 1.3 has this code in place_monster_one() (lines 2341 - 2347 of monster2.c):
```
        if (slp)
        {
                int amount;

                if (r_ptr->sleep == 0)  amount = 0;
                else                                    amount = dieroll(r_ptr->sleep);
```

The similar code in NarSil (in place_new_monster_one(); lines 888 - 894 of mon-make.c) is:

```
        /* Set alertness */
        if (sleep) {
                int amount = 0;

                /* Enforce sleeping if needed */
                if (race->sleep) {
                        amount = race->sleep;
                }
```

So NarSil is setting the sleepiness of monsters with race->sleep not equal to zero to ALERTNESS_ALERT - race->sleep while Sil 1.3 is setting the sleepiness to ALERTNESS_ALERT - randint1(race->sleep).

**Comment by NickMcConnell** [comment]
Excellent, thanks

**Comment by NickMcConnell** [comment]
This is now a bit general to be useful, so I have made a couple of new issues from outstanding bits and am closing this one.
