### ISSUE TITLE
RFE: Christmas Presents

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#393]
Vanilla Sil starts you with a present each game around Christmas time; not sure when it starts but when you open it before Christmas you suffer the typical 3-Sil penalty for that game IIRC. I believe the behaviour continues until New Year's. As for what's in the present, I believe it's guaranteed to be at least "ego" with a high chance of being an artefact.

**Comment by NickMcConnell** [comment]
Still thinking about whether I'm going to do this one

**Comment by NickMcConnell** [comment]
OK, decided that's a no.
