### ISSUE TITLE
When crafting cursed items, starting bonus can be wrong

### ISSUE THREAD

**Issue by Karcharoth** [NickMcConnell/NarSil#397]
When attempting to craft gloves of treachery, they start out granting +1 strength (with commensurate difficulty), but when reduced down to -1 strength they cannot be increased again, as it should be.

**Comment by backwardsEric** [comment]
With #412 , they'll start with a -1 bonus to strength and that cannot be adjusted.  That is the same behavior that I see from Sil 1.3.

**Comment by NickMcConnell** [comment]
So I'm assuming this should be closed

**Comment by backwardsEric** [comment]
#412 has not been applied yet so this issue is still present with the head of the main branch.

**Comment by NickMcConnell** [comment]
Ahh
