### ISSUE TITLE
Smithing menu

### ISSUE THREAD

**Issue by NickMcConnell** [NickMcConnell/NarSil#4]
Is probably functional, but needs some work.

**Comment by wfpeterson79** [comment]
Attached file has a character on a forge with all smithing abilities and 20 smithing
I can navigate the entire menu, selecting items, adding enchantments, artifice, and changing numbers. Occasionally, selecting an item to create shows "(nothing)" as the name, but repeating the selection gives the correct name.
Melt works.
Accept always crashes
[Ardhel - on forge.zip](https://github.com/NickMcConnell/NarSil/files/10934110/Ardhel.-.on.forge.zip)

**Comment by NickMcConnell** [comment]
Thanks, this is super helpful.  I'm a little surprised it works that well...

**Comment by NickMcConnell** [comment]
This needs work on the menu, possibly in ui-menu.c.

**Comment by NickMcConnell** [comment]
As of 0068dfe1f the menu is basically functional (accepting items works, smithing completes successfully), but there still seem to be some issues around what happens to the object when going in and out of submenus, and there's been no testing of artefacts.

**Comment by NickMcConnell** [comment]
As of 505369043 no known bugs and a decent amount of artefact testing done, so I'm closing this.  Any bugs that emerge can be opened as new issues.
