### ISSUE TITLE
Bug: Standard Angband Keyset, Various Commands Nonfuntional

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#40]
Waiting in place via [5], accessing a forge by standing on it and doing [+][5] or Ctrl-d, probably more.

**Comment by NickMcConnell** [comment]
Fixed those, I think, but leaving this open for now.

**Comment by ThatGitMITZE** [comment]
[Tab] functioned as a shortcut to the ability menu from the main screen in Sil; doesn't work here.

**Comment by ThatGitMITZE** [comment]
The final [t] for confirming a target while targetting while throwing doesn't actually do anything; so far the only ways to actually throw AFAICT are either via pure direction or by using ' for target nearest.

**Comment by NickMcConnell** [comment]
Targeting should basically work now, but it still needs improving, see #51.

**Comment by ThatGitMITZE** [comment]
@ doesn't work as a shortcut to the keymap/macro edit menu.

**Comment by NickMcConnell** [comment]
> @ doesn't work as a shortcut to the keymap/macro edit menu.

It doesn't in Angband any more either.  My general policy is to fully replicate Sil gameplay, but not necessarily interface.

**Comment by ThatGitMITZE** [comment]
I'm not really sure why that isn't a thing anymore, frankly; it's common enough in other *bands and I definitely find it convenient to not have to go through one or two other menus to get to it first.
