### ISSUE TITLE
Sil 1.3's handling of Morgoth's song of piercing

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#403]
In Sil 1.3 (see spells1.c:4621-4635; the same logic is still there in Sil-q), if Morgoth is not seen by the player when he begins singing a song of piercing, the message for continuing the song is used instead of the message for starting the song, and Morgoth's state is not updated to indicate that he is singing the song of piercing (I suspect that's an unintended side effect of trying to get the messaging right, but perhaps it is intentional).

In NarSil (song.c's monster_sing()), a monster's song of piercing gets the same treatment as a song of binding or a song of oaths:  when the song is begun there is a "begins a song of" message naming the singer and the singer's state is updated to note that the song is in progress; the text of the message does not depend on whether or not the singer is seen by the player (that seems like a bug to me; EDIT: though for the song of binding and song of oaths it does match what Sil 1.3 does).

**Comment by NickMcConnell** [comment]
I agree.  It should be always only the starting message if the monster is visible, and the state should always be updated.
