### ISSUE TITLE
Bug: Chest/Traps

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#41]
Disarmed a chest, set off a trap, it said that "a noxious vapour escapes from the chest" but there was no obvious effect. Possibly related to #23.

**Comment by NickMcConnell** [comment]
Possibly fixed by 8e27e6906

**Comment by NickMcConnell** [comment]
Was pretty much fixed, I think - final touches in 0c7ce15d1.
