### ISSUE TITLE
Bug: Quivering

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#42]
Apparently I've ended up with spears (inscribed =g@v0 out of reflex) in my quiver; Sil only lets arrows occupy the quiver.

EDIT: Also, the arrows that I had quivered one at a time (#31) are no longer in my quiver, despite me not deequipping them. I suspect it's related to that crash (#32).

**Comment by NickMcConnell** [comment]
Fixed in 705d408af, I believe.
