### ISSUE TITLE
Archers' monster lore does not list an attack bonus

### ISSUE THREAD

**Issue by Karcharoth** [NickMcConnell/NarSil#421]
What it says on the tin - my goblin archers show as "It may fire a shortbow (1d7)", not "It may fire a shortbow (+6, 1d7), for instance. I [resolved this](https://github.com/Karcharoth/Keys-of-Orthanc/commit/eea42a9092a90048ab21aa618d14f08fa133f57f) with a new tiny function in mon-spell.c and an extra few lines incorporating that in mon-lore.c, and it seems to work well enough.

**Comment by NickMcConnell** [comment]
Thanks, merged as [ff78954](https://github.com/NickMcConnell/NarSil/commit/ff78954856260eca5a93ef712545e0764ad1575c)
