### ISSUE TITLE
Foods don't need descriptions

### ISSUE THREAD

**Issue by Karcharoth** [NickMcConnell/NarSil#427]
For instance, examining Lembas already lists all its effects; the descriptions in object.txt are somewhat redundant.

**Comment by NickMcConnell** [comment]
Yes, I kept the Sil descriptions, but also the Angband generated description.  Also the values for lembas are silly (turns fed for is out by a factor of 10, and I don't think it's 3000 percent).

**Comment by NickMcConnell** [comment]
Potions are a similar case.

**Comment by NickMcConnell** [comment]
And horns, and herbs.  This whole effect description thing needs a lot of work.
