### ISSUE TITLE
Spot effects cause out-of-sight pain messages.

### ISSUE THREAD

**Issue by Karcharoth** [NickMcConnell/NarSil#436]
I'm not sure this is actually relevant, as I don't know of a positive-radius damaging Spot effect, but it certainly bothers me. If, say, a giant fire Spot hits an orc, you always get "You hear a cry of pain," visible orc or not. Working on a fix.

**Comment by Karcharoth** [comment]
True of fire breath too, so it's probably a general problem with project().

**Comment by Karcharoth** [comment]
Okay, the problem is that project_m_player_attack() and project_m_monster_attack trigger a hurt message (e.g. catches fire!) only if a monster has a hurt message (and is visible), else if dam > 0 message_pain() triggers. I'm not sure why this isn't already an issue in Vanilla?
This issue can be resolved by [splitting it into two if statements](https://github.com/Karcharoth/Keys-of-Orthanc/commit/8ff5981c9405d22aabee752af850a30212e8a153). It looks a little ugly, but should be good enough.

**Comment by Karcharoth** [comment]
Or, alternatively, monsters could get visible pain messages, e.g. "The cat warrior cries out in pain" when visible? Not sure how Sil did it.

**Comment by NickMcConnell** [comment]
I think the answer is that the projection handler - project_monster_handler_FIRE() or whatever - should *always* set the context->hurt_msg field.  I suspect the check for a hurt message is only to avoid bad things happening if for some reason it isn't set.

And the answer to how Sil did it is with very different code 😄

**Comment by NickMcConnell** [comment]
Yes, in fact I think your fix was correct - now in e21f503.
