### ISSUE TITLE
Exchange Places can give a misleading message (mostly irrelevant)

### ISSUE THREAD

**Issue by Karcharoth** [NickMcConnell/NarSil#437]
Exchange Places will say "You cannot enter the wall" if used on a closed door with a PASS_DOOR monster, because `square_iswall()` includes them. I think it [should be](https://github.com/Karcharoth/Keys-of-Orthanc/commit/a24056817f521b16d92ea3f02f2f62d7eb144654) `square_isrock()` instead?

**Comment by NickMcConnell** [comment]
Fixed in 0ece402
