### ISSUE TITLE
PASS_DOOR doesn't work on secret doors.

### ISSUE THREAD

**Issue by Karcharoth** [NickMcConnell/NarSil#438]
As far as I can tell, a monster can't pass under a door if the player hasn't spotted the door. This seems like a gross miscarriage of justice - how would they even know?! Does it work this way in Sil?

**Comment by backwardsEric** [comment]
From what I see, PASS_DOOR monsters do go through undetected secret doors:

1) Modify tutorial.txt to place a Shadow at (1,23) which is just north of the secret door in the first room.
2) Start the tutorial and use '1' to move to the lower left corner of the first room.
3) Use the debugging commands to get the character a horn of blasting.  Use the horn twice on the wall to the south to make some noise.
4) Press '5' repeatedly to see if something enters the room and attacks the player.  When I did this, I got to turn 10 before I got the message "Something touches you."  So the Shadow went through the secret door as any other path to the first room would take much longer for the shadow to get there.

That agrees with the logic in mon-move.c's process_move():  the square_iswall() test will be true for walls, closed doors, and secret doors and the square_iscloseddoor() test that follows after that will be true for revealed closed doors and secret doors.

The logic for TUNNEL_WALL (i.e. Morgoth) there looks wrong however:  the rf_has(race->flags, RF_TUNNEL_WALL) && !square_iswall(cave, next) test contradicts the earlier square_iswall() test and will always be false.  It should be rf_has(race->flags, RF_TUNNEL_WALL) && !square_iscloseddoor(cave, next) which is what Sil 1.3 has (see melee2.c:3677).

**Comment by Karcharoth** [comment]
Hmm, I think I'm wrong then; I'll test some more. I know I had an odd situation involving a custom monster with Territorial and Pass_door, and I'm fairly sure they could only get to me once I discovered the door. But yeah, more testing needed.

**Comment by NickMcConnell** [comment]
Leaving this open for now, I'll close it as not an issue after a bit if there's no new info

**Comment by NickMcConnell** [comment]
OK, closing now.
