### ISSUE TITLE
Running off the map crashes the game

### ISSUE THREAD

**Issue by Karcharoth** [NickMcConnell/NarSil#446]
E.g. using . to move off the map at the Gates will crash the game by triggering the assert on line 900 of cave-square.c, while moving normally will not. 
I'm a little iffy on the whole "win game if out of bounds" thing - it seems like it'll cause a few more troubles like this.

**Comment by NickMcConnell** [comment]
Yes, I was kind of thinking the same thing - I just copied how Sil did it.

**Comment by NickMcConnell** [comment]
Am I right in guessing that the call to square() that causes the crash is in run_test() at line 580 of player-path.c?

**Comment by Karcharoth** [comment]
Well, upon some testing there seem to be at least two separate things that crash it - running (.) adjacent to the edge, and simply being adjacent to the edge while any monster is in view. But yes, prinft() testing says the running crash is due to line 580.

**Comment by NickMcConnell** [comment]
OK, I've just made it that stepping onto the edge wins the game, and added a check for arriving there by running.
