### ISSUE TITLE
Matching Sił 1.3's limit of one greater vault per level

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#474]
Sil 1.3 limits greater vaults to one per level:  see its generate.c:2952-2956.  NarSil does not appear to have such a limit:  I only see the vault_name field of the chunk used to issue a message when entering a vault or to put a note in the character's history that a vault was missed.

It is easy enough to add a check on c->vault_name in build_greater_vault() to mimic what Sil 1.3 does, but was the limit dropped intentionally?

**Comment by Karcharoth** [comment]
Having fun with alternative characters that look like 'l' in the title?
