### ISSUE TITLE
Lighting chance for crossed rooms

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#479]
The current logic in NarSil, see gen-room.c's build_crossed(), is 'if (c->depth <= randint1(z_info->dun_depth)) light = true;'.  That does not match Sil 1.3 or sil-q, which use the equivalent of 'if (c->depth < randint1(z_info->dun_depth)) light = true;' (see Sil 1.3's generate.c:1970 and sil-q's generate.c:2143-2144).

The probability for lighting a crossed room in NarSil, Sil 1.3, and sil-q does not match the comment in the code, which says 100% at 50 feet and 0% at 1000 feet.  Either would need to change the comment or use 'if (c->depth <= randint1(z_info->dun_depth - 1)) light = true;' to fix that.

**Comment by NickMcConnell** [comment]
I'm going to go with the comment as the intent of Sil 1.3.
