### ISSUE TITLE
Bug: Forging/Jewellery

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#48]
Forging seems to have a number of problems with it currently; I noticed that various pieces of jewellery (at least) do not appear to have (or maybe it's just that it doesn't display) all the attributes they normally do (for example, an amulet of the blessed realm only states that it sustains grace in its description), going to forge something actually requires that you *manually* wait in place or whatever while forging, and once forging an object is completed it causes a crash.

EDIT: Also, I notice that after a few of the forging completions crashes that I've somehow gotten a *lot* of bonus attributes; I think Narsil is doing things with memory it shouldn't again.

**Comment by NickMcConnell** [comment]
I believe this is fixed in 0068dfe1f

**Comment by NickMcConnell** [comment]
Calling this done.
