### ISSUE TITLE
Bug: Lights/Fuel

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#49]
While waiting for gorcrow-caused blindness to wear off, I noticed that my starting torch reached 1 turn of fuel, and is staying there.

**Comment by NickMcConnell** [comment]
Interestingly, this is a feature in Sil, Angband and likely all variants - if you're blind, and your light goes to 0, it's put back to 1.  Probably as the result of someone complaining years ago about how they were blind and their light went out so they died.  Or something.

**Comment by ThatGitMITZE** [comment]
Seems excessively and nonsensically generous to me, but whatever :/
