### ISSUE TITLE
Light use

### ISSUE THREAD

**Issue by NickMcConnell** [NickMcConnell/NarSil#5]
Torches seem to be burning out too fast.

**Comment by ThatGitMITZE** [comment]
I'm noticing that I seem to get slowed for no apparent reason, that might be a factor.

**Comment by NickMcConnell** [comment]
Yep, this one's been there since I first got it running, and I haven't managed to track it down yet.  Filed a [separate bug](https://github.com/NickMcConnell/Sil/issues/11) for it.
