### ISSUE TITLE
Bug: Character Sheet Min/Depth

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#50]
1) I don't think the timer is working correctly; fully-ish exploring each level, I'm on 150' and the game claims the min depth is still 50', I feel that's not right (though I have nothing concrete to back that up, I don't know overly much about Sil's timer).

2) In addition to the previous, my current depth (150') is displayed in yellow, despite being deeper than the min depth; this also seems wrong.

**Comment by ThatGitMITZE** [comment]
The first point there might be an error on my part; in my current game the timer seems to be working as it should. More testing needed for verification.

**Comment by NickMcConnell** [comment]
There definitely were problems with the main game loop which could have affected timing, and which I've recently fixed.  I'm not convinced I've got the main loop completely correct, but it's certainly better than it was.
