### ISSUE TITLE
Bug: Ranged Attacks & Stationary Enemies

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#55]
Shooting/Throwing at stationary enemies seems to invoke a crash; so far I've only noticed it with tanglethorns and madthorns.

**Comment by ThatGitMITZE** [comment]
May not be fixed; throwing a throwing axe at a sleeping gorcrow invokes a crash for me now.

**Comment by NickMcConnell** [comment]
I can't reproduce this so far.

**Comment by ThatGitMITZE** [comment]
Crashes 100% of the time when I throw something, everything I've tried, at an enemy or no, on the webserver. I'm in a position to replicate it, next time we're both available on there.

**Comment by NickMcConnell** [comment]
Quick test on angband.live gave me no crash (new character throwing its curved sword).
