### ISSUE TITLE
Bug: Monster Recall

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#61]
...has a bunch of formatting issues with it; saw a bunch of extraneous "He ." in there, for instance. Forget what I was looking at, though.

**Comment by ThatGitMITZE** [comment]
Looking again, it seems like it mostly seems to occur wherever stuff like damage, armor, etc. should be.

**Comment by NickMcConnell** [comment]
I'm calling this fixed by b393d391d, if there's anything still wrong we can reopen this or open a specific issue.
