### ISSUE TITLE
Dodgy combat numbers

### ISSUE THREAD

**Issue by NickMcConnell** [NickMcConnell/NarSil#62]
See [this post](http://angband.oook.cz/forum/showthread.php?p=160536#post160536).

**Comment by ThatGitMITZE** [comment]
Finally have something concrete here:

Hummerhorns have [+14] EV and no PROT; I was hitting some with thrown spears (1d9) this past game and some did no damage at all, which with no PROT to roll against I would think shouldn't be possible.

**Comment by NickMcConnell** [comment]
Turns out negatives on the hit roll were being treated as hits for message purposes (🙄), so misses were looking like hits.

**Comment by NickMcConnell** [comment]
I'm calling this done, if another concrete example comes up we can file a new bug.
