### ISSUE TITLE
Bug: Special Rooms/Feature Generation

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#64]
I'm noticing that a bunch of rooms seem to generate weirdly; pillared halls without all the pillars, forge rooms without forges, that one circular room with a one-tile walkable rim around a pit of chasms but the chasms don't generate everywhere they should. For examples.

**Comment by NickMcConnell** [comment]
It looks like the rooms are generating correctly, but then are getting overwritten by the tunneling code.  So it's likely to be a problem in tunnel_ok().
