### ISSUE TITLE
Bug: (Great Helm of) Terror

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#67]
Wearing it, game won't let me attack at all, treating me like I always am afeared; the way it's supposed to work is that if you take sufficient damage in either one turn or one blow (not sure which) you're inflicted with fear.

**Comment by ThatGitMITZE** [comment]
wobbly says it's supposed to be, if you take a certain % of health in one hit, roll a Will check, becoming scared on failure.

**Comment by NickMcConnell** [comment]
Well, the skill check in the saving throw for timed effects was reversed.  I fixed it in commit a9c64de6f today, so this is possibly fixed.

**Comment by ThatGitMITZE** [comment]
I'm not so sure; found another Terror piece this past game and it still was not letting me attack while wearing it.
