### ISSUE TITLE
Bug: Nonfunctional Traps

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#69]
Traps don't appear to actually have effects besides the one on the message line; flash traps don't blind, caltrops don't slow, etc.

**Comment by NickMcConnell** [comment]
I believe all traps work now, leaving open for a bit.

**Comment by ThatGitMITZE** [comment]
I'm not _entirely_ sure that's true, I feel that I stumbled into some traps that caused a crash in the most recent game...maybe dart traps?

**Comment by NickMcConnell** [comment]
I have certainly tested all the traps and had success with them, but it's possible not every case happened.

**Comment by ThatGitMITZE** [comment]
It's possible I misremember; I'll try and pay closer attention next game, make sure traps were involved.

**Comment by ThatGitMITZE** [comment]
Confirmed at least one trap not working (at least how it did in Sil); Gas (Confusion) traps in Sil actually procced a confusion ball (I think with radius 1 or 2), and monsters within the radius could also be confused (probably making a Will roll against it; I'm not entirely positive of the mechanics behind it).

**Comment by NickMcConnell** [comment]
Calling this done.

**Comment by ThatGitMITZE** [comment]
Web Traps don't appear to be generating a spider as they should when you stumble into them now.
