### ISSUE TITLE
Crash: Character Creation, Starting Over Afterwards

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#70]
Getting to the end of character creation, and then choosing to start over, causes a crash.

**Comment by NickMcConnell** [comment]
Can't verify this, on my dev machine or angband.live.

**Comment by ThatGitMITZE** [comment]
Still crashes for me, but I do note that it doesn't happen if you just hit [Enter] a bunch of times until you get to that point; seems to only happen for me if I make any changes during the birth.
