### ISSUE TITLE
Other post-4.2.4 Vanilla Angband commits to bring over to NarSil

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#705]
For these commits, it wasn't clear if porting them from Vanilla Angband would be useful to NarSil or Beleriand:

1. [418dd9a6d1edf63e3906bb59b4607041d6f294f6](https://github.com/angband/angband/commit/418dd9a6d1edf63e3906bb59b4607041d6f294f6) : use hardwired code names to refer to terrain in data and preference files rather than the names set in terrain.txt.  A side effect of that change was to redo the feature knowledge menu to use terrain flags for grouping rather than grouping by the default graphic symbol.  It should be possible to just pull that out if that is useful but the hardwired code names are not.
2. [41646c4371517fbfed528fa664164a000789be41](https://github.com/angband/angband/commit/41646c4371517fbfed528fa664164a000789be41) with corrections in [398d7ceaa22240e0a0dc9236b0a6ffe2d3e8947f](https://github.com/angband/angband/commit/398d7ceaa22240e0a0dc9236b0a6ffe2d3e8947f) and [18ed034cd73cd679d603bde52338ca22dc9df39b](https://github.com/angband/angband/commit/18ed034cd73cd679d603bde52338ca22dc9df39b) : use a data file to configure the monster categories in the knowledge menu rather than hardwired categories in ui-knowledge.c based on the UNIQUE flag and the default graphic symbol.
3. https://github.com/angband/angband/commit/c833e0ff08bd5ae32cfd28e9612754284741bd6d and https://github.com/angband/angband/commit/be45b76f21d89d01d481b1366a358fca39aa3e6f : add commands for auto-exploring and extend the staircase commands to navigate to the nearest known staircase when not already on a staircase; the second commit adds additional keys to access the autoexploring commands from the targeting interface.  There were also additional commits to change pathfinding so it was more convenient/efficient to use for auto-exploring.  Those I'll likely port over anyways with the exception of https://github.com/angband/angband/commit/481c6053eb6b2883e8fdcfacb24b77d4301c88c0 , to let pathfinding automatically open doors or dig rubble in some cases:  that one seems appropriate only if the auto-explore commands are there.

Is there any of those that you'd like to see in NarSil?

**Comment by backwardsEric** [comment]
Two other commits that I'm not certain if you'd like them carried over:

1. https://github.com/angband/angband/commit/b0b424810bb7cd3613bdb01d5b24b3e0cd829d79 and the correction in https://github.com/angband/angband/commit/c49d0003deb0ff61026bd9084c0c48811059de94 which remove the Angband.live-specific keymaps.  If that's applied, I assume something would have to be changed with NarSil's configuration on Angband.live so running does not break there.
2. https://github.com/angband/angband/commit/2a533f258eeb80305fb3fef74093c5a486b98f7b to replace suicide with retire.

**Comment by NickMcConnell** [comment]
From the first lot: 1 and 2 seem good.  I'm still not sold on auto-explore, let's say not 1.3 at all, and I'll reconsider when 1.4 is out.
The other two seem like a good idea I think - we can work out about angband.live later.
My current plan is
 - release 1.3.1, with the aim of still updating the 1.3.x branch as a reproduction of Sil 1.3;
 - probably at the same time release 1.4.0, which is basically ready as the id branch currently in the repo; it will likely still have some issues, but I want to get i tout and have it as the main branch being worked on;
 - not too long after get the latest attempt at Beleriand (which I am working on at the moment) at least in the repo as the main branch, but I want to make sure it basically runs without crashing too often at least, even if the gameplay is very underdeveloped.
I have been ready to do the first two for a few weeks, but it seemed sensible to wait while you were still doing a lot of your from-Vanilla series.  Given all this, any suggestions on how the timing would work best would be most welcome.

**Comment by backwardsEric** [comment]
As for timing, it would likely be a week or so before I finish off the commits from Vanilla Angband.  That would largely catch NarSil up with what was incorporated into 4.2.5 and also the post 4.2.5 commits that don't seem likely to need further revisions.

**Comment by NickMcConnell** [comment]
OK, brilliant.  I'll look to do my NarSil releases at that point.

**Comment by backwardsEric** [comment]
The terrain code changes were done in https://github.com/NickMcConnell/NarSil/pull/715 .  Configuring the monster categories by a file in lib/gamedata was done in https://github.com/NickMcConnell/NarSil/pull/729 .  Removing the angband.live keymaps was done in https://github.com/NickMcConnell/NarSil/pull/712 .  Replacing suicide with retire was done in https://github.com/NickMcConnell/NarSil/pull/731 .  Those last two commits did miss updating the file lists for Visual Studio; that (along with other updates to those file lists) is in https://github.com/NickMcConnell/NarSil/pull/736 .

I decided to limit the pathfinding changes after Vanilla Angband's 419b9fa8e54aad5a44f9d8cdb465d0447493d777 that I'd port over to the one in https://github.com/NickMcConnell/NarSil/pull/739 .
