### ISSUE TITLE
Bug: Connected Stairs

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#72]
birth_discon_stairs is set to [no] but I don't always spawn on top of an/a upstairs/downstairs when I take a/an downstairs/upstairs.

**Comment by NickMcConnell** [comment]
Running stats on disconnected levels shows that with player->upkeep->create_stair set to an up stair, there are cases of the player generating not on a stair.

**Comment by NickMcConnell** [comment]
🤞
