### ISSUE TITLE
Bug: Superfluous Checks on No Sight

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#73]
Was asked if I really wanted to step into a chasm I couldn't see because it was in the radius of a darkthorn; this shouldn't happen, I nominally should have just fell down it.

EDIT: Also IDed an _Imprisonment when I couldn't actually see the effects; I somehow knew that doors I had nominal LOS on closed despite not having actual LOS on them (because of insufficent light) and them not suddenly blocking any lit squares. (EDIT2: Actually, all consumables ID on use right away, so this was probably a relic of that.)

**Comment by NickMcConnell** [comment]
ID of _Imprisonment should be exactly as in Sil (which works equally whether blind or not), ditto for _Freedom.  This has made me notice that _Slumber and _Majesty weren't working quite right; I've fixed them in 9510d6c91.

I haven't chased down the chasm thing yet.

**Comment by ThatGitMITZE** [comment]
You can also detect traps (that you're not stumbling into) just fine while blind.

**Comment by NickMcConnell** [comment]
Trap detection is penalised but not forbidden when blind; the code looks OK.
