### ISSUE TITLE
Flavors 141 through 150

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#733]
In Sil and Sil-q, flavors 141 through 150 are used for the Easter eggs, with special logic to show herbs as Easter eggs on Easter.  In NarSil those flavors are used for herbs.  The flavor names for those flavors are not particularly herb-like ("Sky Blue" and "Pink" for instance) and for Microchasm's tiles, there are 11 herb-like entries and 10 that look something like Easter eggs.

Should flavors 141 through 150 be dropped at the expense of having existing games reload with flavor assignments that are not consistent with what was there before?

**Comment by NickMcConnell** [comment]
I think yes
