### ISSUE TITLE
Truncation on type conversion warnings from msbuild

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#735]
With the current head, these lines triggered warnings that do not happen with Vanilla Angband about possible loss of data from type conversions:

- [x] cave-fire.c:608,618,621 convert long to uint8_t: 'vinfo[e].slope_fire_index1 = tmp0;', 'vinfo[e].slope_fire_index1 = tmp1;' and 'vinfo[e].slope_fire_index2 = tmp2;'
- [x] generate.c:350 converts size_t to uint8_t: 'v->wid = strlen(desc);'
- [x] mon-make.c:704,911 convert uint16_t to uint8_t: 'mon->wandering_dist = z_info->wander_range;' and 'mon->mana = z_info->mana_max;'
- [x] mon-move.c:3552 converts uint16_t to uint8_t: 'if (mon->mana > z_info->mana_max) mon->mana = z_info->mana_max;'
- [x] obj-smith.c:518 converts uint16_t to uint8_t: 'new->number = obj->weight;'
- [x] ui-combat.c:126,131,136,154 convert wchar_t to char: 'combat_rolls[0][combat_number].attacker_char = square_feat(...)->d_char;', 'combat_rolls[0][combat_number].attacker_char = attacker.which.trap->kind->d_char;', 'combat_rolls[0][combat_number].attacker_char = race1->d_char;', 'combat_rolls[0][combat_number].defender_char = race2->d_char;'
- [x] with the changes as of 2024/10/31 there's also a warning for save.c:925 converting a size_t to uint16_t: 'wr_u16b(i);'

**Comment by NickMcConnell** [comment]
This should be all done now.
