### ISSUE TITLE
Crash: Whispering Shadows

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#79]
Just had a crash fighting a whispering shadow; I'm guessing some factor of its attack doesn't work right, maybe the ignores-armor bit.

**Comment by NickMcConnell** [comment]
First attempt failed to reproduce this.

**Comment by ThatGitMITZE** [comment]
It's possible it was related to some of the other problems with non-standard melee (like Delthaur) and has since been fixed; I'll keep an eye out.

**Comment by NickMcConnell** [comment]
Should be done.
