### ISSUE TITLE
Time interval for displaying damage notifications on the map

### ISSUE THREAD

**Issue by backwardsEric** [NickMcConnell/NarSil#813]
For that interval, Sil 1.3 and Sil-q uses 25 times the base delay factor (default value of that base delay factor is 5 milliseconds).  See cmd1.c:3190 in Sil 1.3 and cmd1.c:3574 in Sil-q.

NarSil uses the base delay factor (default value of that base delay factor is 40 milliseconds).  See ui-display.c:1513.

For me with the default delay factor and Microchasm's tiles in the macOS frontend, NarSil's behavior is a bit too quick to really make out the digit displayed on the map.  Perhaps use three times the base delay factor in ui-display.c's display_hit()?

**Comment by NickMcConnell** [comment]
This sounds like a good idea.  Given that I haven't pulled in #812 and #814 yet, would it be simplest just to amend those?
