### ISSUE TITLE
Crash: Mewlips

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#816]
I seem to be getting a consistent crash when I run into Mewlips—I'm guessing when they use their invoke fear action or whatever, but I can't be sure.

**Comment by backwardsEric** [comment]
Summoned a mewlip via the debug commands in the tutorial, its fear effect didn't trigger a crash, but likely (the crash happened before the message was printed) its forgetting effect did.  The top of the call stack at the point of the crash was:

1. ignore_known_item_ok(p=0x000061a000014a80, obj=0x00006100000dbd40) at obj-ignore.c:601
2. map_info(grid=(x = 17, y = 26), g=0x00007ff7bfefc320) at cave-map.c:155
3. prt_map_aux at ui-map.c:666
4. prt_map at ui-map.c:711
5. update_maps(type=EVENT_MAP, data=0x00007ff7bfefd4c0, user=0x000061100006a6c0) at ui-display.c:1099
6. game_event_dispatch(type=EVENT_MAP, data=0x00007ff7bfefd4c0) at game-event.c:43
7. event_signal_point(type=EVENT_MAP, x=-1, y=-1) at game-event.c:160
8. redraw_stuff(p=0x000061a000014a80) at player-calcs.c:1434
9. pre_process_player at game-world.c:617
10. run_game_loop at game-world.c:1077
11. play_game(mode=GAME_TUTORIAL) at ui-game.c:932

In ignore_known_item_ok(), base_obj was NULL and obj->oidx was zero.
