### ISSUE TITLE
Bug: Webs

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#85]
I don't think the check to burst free from a web is happening; can't be sure because I died before I realized what was happening, but I triggered a spider web trap, and I believe the web was created on my square, but I think the game was letting me act as normal instead of making me do STR checks to shake free from it.

**Comment by NickMcConnell** [comment]
I have seen failure to escape from a web, but I'll check it.

**Comment by ThatGitMITZE** [comment]
Note that when I say "act as normal," I mean that I continued to press in the direction of the spider and got no attempt-to-break-free messages that I saw in the log afterwards; instead repeatedly I attacked, got attacked, and told something to the effect that "it's very hard to hit and dodge while in a web." :/
