### ISSUE TITLE
RFE/Bug: Autopickup Throwns

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#88]
In Sil, anything you've thrown is automatically picked up on walkover; requesting either that functionality be reimplemented, or that the {=g} inscription be implemented to do the same thing (it already exists in a few other *bands; Henglikes, at least, I believe).

**Comment by backwardsEric** [comment]
Besides thrown items, missiles that were launched by the player are also automatically picked up on walkover in Sil but are not automatically picked up in NarSil (at least with the default options).

**Comment by NickMcConnell** [comment]
Fixed in 74cf6c48c
