### ISSUE TITLE
Bug: Pseudo-ID

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#92]
I just realized that things aren't automatically pseudo-IDed as in Sil; normally a basic character without e.g. Loremaster is supposed to know an object isn't mundane, even if they can't tell whether if it's cursed or ego or artefact.

**Comment by NickMcConnell** [comment]
Is this the same as #36?

**Comment by ThatGitMITZE** [comment]
Yes, sorry; so many bug I've started to lose track of things :)
