### ISSUE TITLE
Bug: Art ID Experience Gain

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#93]
You don't appear to gain any experience for IDing an art (or at least I didn't just now using a wizardmoded _Understanding on a wizardmoded Thingol).

**Comment by ThatGitMITZE** [comment]
Actually it might have been a screen refresh problem; checking again I do seem to be getting exp for art ID now (though it's supposed to be 200 for arts and 100 for flavors and egos; currently everything is 100).

**Comment by NickMcConnell** [comment]
Pretty sure it's 100 for arts too - can't actually check 1.3.0 currently, but that's what it is in Sil-q.

**Comment by NickMcConnell** [comment]
Can confirm, Sil 1.3.0 code has 100 😀

**Comment by ThatGitMITZE** [comment]
Well, you're right, as far as I can tell; checked the code myself, what I could find said 100, playtested it in Sil myself, experience said 100, asked the chat, they said 100.

I dunno why I thought it was 200 all this time, except maybe I had memorized it from the manual and in that specific case the manual was being a big fat fucking liar. :(

I am irrationally annoyed about this.

**Comment by ThatGitMITZE** [comment]
wobbly found the thing, apparently art ID exp and unique exp was reduced in Sil v1.2 . . . the manual just wasn't updated with the code.
