### ISSUE TITLE
Bug: Equipment-Granted Abilities

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#94]
Are displayed in red in the ability menu...I can't actually tell if they're active or not, but intuitively by the color they're not and you don't appear to be able to switch them on/off.

**Comment by ThatGitMITZE** [comment]
Also apparently they don't display upon [I]nspecting the relevant piece of equipment, though there's still the indication in the ability menu.

**Comment by ThatGitMITZE** [comment]
Actually I'm wondering if this and #95 are connected; I just noticed that not even the ability menu has the indicators now, even though I'm positive they did before, and I'm pretty sure I've had crashes/hangs/forcequits since then.

**Comment by ThatGitMITZE** [comment]
Possibly not quite fixed yet; equipment now provides abilities as it should when worn, but I had a situation where I went from a shortbow of quickness (granting me Rapid Fire) to Belthronding (no ability), and I somehow kept the Rapid Fire.

**Comment by NickMcConnell** [comment]
Yep, will check
