### ISSUE TITLE
Crash: Artifact Leather Gloves

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#95]
Wizardmoded one of either Rumil or Brethil and tried equipping it; it caused the game to hang. Forcedquit, wizardmoded the other, and that caused the game to crash.

Have tried both multiple times, and it's not being consistent in causing problems though.

**Comment by ThatGitMITZE** [comment]
Just had the hang happen again going to wear Taur-nu-Fuin, and then the server crashed after a forcedquit.

I suspect NarSil is doing Narghty things again.

**Comment by ThatGitMITZE** [comment]
You know, I seem to be able to reproduce the hangs/crashes not consistently but often, using wizardmode on the webserver.

**Comment by NickMcConnell** [comment]
Not sure how much this is happening now, I'll close it soon if there's nothing further.

**Comment by ThatGitMITZE** [comment]
Yeah I suspect this was a consequence of the problems with abilities on equipment; I pretty much didn't run into it once I stopped trying to wizardmode that stuff, and since you fixed it I didn't run into it at all last game.

**Comment by NickMcConnell** [comment]
Closing this now.
