### ISSUE TITLE
Bug: Riposte Ability

### ISSUE THREAD

**Issue by ThatGitMITZE** [NickMcConnell/NarSil#99]
I don't think it's working; I've not seen it proc yet, or at least aren't seeing any messages that it's proccing.

EDIT: Okay, I'm seeing it proc, but I'm not convinced it's working as it should; feel like I'm seeing less ripostes than I should considering my EV.

**Comment by NickMcConnell** [comment]
It seems to be working now, and I can't see anything wrong with the code.  It is likely that problems with the main game loop were making it less effective, as the game was counting a previous riposte as still being current.
